kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: auth
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "0" }
spec:
  description: auth proxy
  sourceRepos: ["*"]
  destinations: [{ namespace: "*", server: "*" }]
  clusterResourceWhitelist: [{ group: "*", kind: "*" }]

---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: auth
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "2" }
spec:
  project: auth
  source:
    repoURL: https://github.com/MP281X/argocd
    targetRevision: HEAD
    path: app/auth
  destination: { server: https://kubernetes.default.svc, namespace: argocd }
  syncPolicy:
    syncOptions: [CreateNamespace=true]
    automated: { selfHeal: true, prune: true }
