apiVersion: v1
kind: Namespace
metadata: { name: argo-events }

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
spec:
  project: ci-cd
  source:
    chart: argo-events
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.1.2
  destination:
    namespace: argo-events
    server: https://kubernetes.default.svc
  syncPolicy: { automated: { prune: true, selfHeal: true } }

---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: kaniko
  namespace: kaniko 
spec:
  service:
    ports:
      - port: 80
        targetPort: 80
  webhook:
    github:
      port: "80"
      endpoint: /
      method: POST

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argo-workflow
  namespace: kaniko
  annotations:
    kubernetes.io/ingress.class: traefik
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`argo-events.mp281x.xyz`)
      kind: Rule
      services: [{ name: kaniko, port: 80 }]
