
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: kaniko
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    github_token: AgBy8fE8fh4bdcxeSAkpQ24g3hjzTia767E25kFSXXqubGGzJIQdJLHBosb7zA7dgEh7z4jIjIq+EgtprVBopt2KOh3+KmH24K77Azwi9Y1wBfy7vj7uWReCWwhntCms8l6seyFNZd4JiElcEsfEUCLmCIh/GVb1OsCUlyoe2NPc8VcvNAPicgrSWXVW63l/rzUby3VYh8+xn3jFXqJ+pRdbEFCIaYCxbbFX0Dj3F+hTdbjEXiacK0xLc+Q7eMbfrBMLLbQRVaymbIA2Ubb0AkOkl7IlmFxld6mlunfU0N6BCFNndTJJE4BV/JNTkQ6Hxr10bwC6qNnZw1u/d6TsIq4tOHdHOHUIGUVVuMz26tWdcR1Nf/RiBYIipx8T6y2DQVGd1Woqb6Ih439E2iU2gKbPKEXCcKSAjBzKHefrLzHS11wHlrVDypvI+4NHUPhe28DEZ2lL8g7hDNOyfQbzmqdSvEZu+wpICi6qJ7LEeETONHKtOe3j4KQNA/RqoKxRAs4D2O0Bhd0QyOtjO5qJ5zSg0gRWPGrOBrJaaFAzW2UpvZAg3iQ5nCtPVryFEFSDhX3XAMvuxlLnQVhVbz38KlqXGuggavLh2MddRGKRZuiEOxRpf9Fv/YReuv3R+O53JdKPX+zWRK/0IpJL++EXdEnpuQcRpNk8N3U5SRd35BA5zIAQ1ICc6PiU6CEWCRwTiMSSpQjT5HOiYVP8KmRDBgDqeBaNBqmAvQZ0KcfzytuxxCZ3w+mQJupy

