
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: kaniko
  annotations: { sealedsecrets.bitnami.com/cluster-wide: 'true' }
spec:
  encryptedData:
    github_token: AgAwwWCuPrgSB+eOCe/Dq+gStjjhAkqDOuNGXptoTF7e+B9thd+6nH7GajLmL6Q6jf4d3Fv0FqKqz3TCUZqByk3y3CCWbBy+0RpV/lp1gzx3JCN0Xk7veqtrm42pJ0goJZ0n4qwg2syZPphCH31EtSFHGE5pM/oknfFqc4ra4cDhy+wssvFyEvmmpYbvhELhxCTmJ79BLB03nmeQBr0plCZRFW6n7V+zLkhF1I0Gr413PDjkp7k9K4giDKkpr7DZ2gu0lZ4p1/lwJ383UBYGVgOdLaPeyThJJa1f0WHGyuuwbSYAGxm8fUlXbm/x/nAgClVikBDYGxj4kFayRH80sHYgRb6wVhs6Awc2EXb/4dgFnIF5qAyL7J7WJvo+sMTZgTHNZ35bWu5e5gXmXDw6EdQpR6mXO3HF8lnzrF9Utox2S1mL60s723+4+MmLdWUykSe5uiIS4u518rDel4tWHZ7a8ckmbyBRVsV5UHL6D9IUVQWzp5qpnOgFce0yBQeZ54ntQIjW0YWcpXaMt4e8zWvwiR4E8dDPZ4bBvbXpX7xwMpew2P3j2pMAt4PfTq3v4NFmKU215+qBDeC1EPwxk2ZV51Lb4GWcNahiqfhAtLOLbirrORpUMadz2c7d9aQ1Ez9YlVop7HdUpcQ76AwZuBBD/oNQJ875giOchEbftkiNux7DC8MEezL8aU+/Ze5adRqVTNCWbACAs+pn7LdQPkgCfzB0v92aM+B8RrhlxGDBnePy2mtcUCOs

