
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: kaniko
  annotations: { sealedsecrets.bitnami.com/cluster-wide: 'true' }
spec:
  encryptedData:
    github_token: AgAxvIGpWuEjvTviFdzsJM6YNpmwVsaq0BjFSOuaysJ+0ekG2sOx4XqrwkRmAggQHGRfbdbzgzOF8dafhuGy+3aar2Sp8wnT/MiMs40DnrpnntnsSen8SqFlaFMHWnrRjx+LzBvrZGV5rfS82RP7gAZb/cY7KR1A6JW0VmlEN24dWOvJVv9RXDzn5oUiIBU0/JQwhN3CdhIvnP0NZykxv70AIYeYHUbMEZFTwrRSpBwwXDXnjKTH6/A2kuy5ADkbN+BsScg8PHg4Yuu+NDSiG4wRkxqNLW5+AU9jjygjnhwfWSghpWd/IkKG3rdidSzhlcwJMHHXyv3mUgL3W4uyK6eHcAnTSiP5c9A3IYwmkeryVyMEcciAG7/Xdk8je9Z2Rg4rv56p9Mibn+upZ1dF1RDjLY/MsudnKgzZANrOyDdJoKOtH1KoZbBmXwzmjgxFtQ3rQ1PbAym/R/VQrzNeTzqA9c9y68mvQtZ1B8Kga+WvWUn9uFzfiNMpBj1X2rEnFHpOqUyU7Ao/ePrOI33lwGup9G95BjX/D1ICRyrVnJRhuCK3+wj3ql7IKB7rJtXpfN9exkxP4j+ajXwzwT2P7ILJZdITW0ZuH3w5bc8TOnOc3G/MB8/MJAb2SUZuzIH6we+AG/Dda0dE4bnLs5o/8OPropeJuSbUFyxBymnJl30WY1xzDiZWyfNur9z5ej0/eEB/lkYile1hYGFxUpi40c41tk+8MqxyCRUm2zKdJcdPnn/z7wSvYwmD

