
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: kaniko
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    github_token: AgAqxKgXC2G0c+Y5xZkeUa7rxdHRil+lD6HsC58BMfOVgoRpuRycocMmPLrLIfhzfuU2ybT6xkhpeMc6zs++5NW9i1YeZEMBgvSsUXzMHO7d94+UJEf08jeDQZ00DtqYktQ276YGEF/PDUlCtbMMFJRHiC3viU7Mm0/21deB7MP/w9Lvk/UjnC9pjJw+DKtU4MKvX6W8RpiEOLdniZZcZtuAUmwUVbzchprUv2HZvH2XESJ9pXGKcB/cxnETQPMjhPJD73WxFJagVyGD22uQYKM5bdQBDnjFfh1JMX53aiBHA9oYoFzmrTjtDxARMig3R+icYAR0HctzWvyVrB1IoCT7wjIeLRsL5M2K+G0npSxFG+jgYlYoYzjAEAPfbpBkcTJK2Tjoecm2wH/D2Btk1LB3Y+zA9sIMKvUeo3Qj5Q3q7HNwtT84dA/ar1xUokDgGrwPZR5l856V1LFf/zl2sFnlb6L720ISzEZWIOUTA1ZYMQ7qp3ORjkU8CYEjcMJDCAOTWcSLNOd8jO4KbRx4/CqZN+3hgiDP46Wv5P6kYaeqydAbSi9M7CzY34UZMaOkLstEcVCzM00IOqb+ndp5J5FWYNXp9mfOBQ4B3M3ihibCWBlaHLw6ZL/kgzvT75IVsuCuGdl+VeUP4GfJ5cruPRC1lQNb/QvEszaGMj+WIdFKCp5cSBdyfrKI9bQZPyBjQElqM1kL8K9oPCPBmjMBkZZK2BG8V8JSgHqFtVHCzEpXxHBZNSNL1uuP

