apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: infrastructure
  source:
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.22.8
    helm:
      values: |-
        installCRDs: true
        replicaCount: 1
        server: { extraArgs: [--auth-mode=server] }
  destination:
    namespace: argo-workflows
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: { prune: true, selfHeal: true }
