apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "4" }
spec:
  project: infrastructure
  source:
    chart: authelia
    repoURL: https://charts.authelia.com
    targetRevision: 0.8.38
  destination:
    namespace: authelia
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions: [CreateNamespace=true]
    automated: { prune: true, selfHeal: true }
