apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "2" }
spec:
  project: infrastructure
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.9.1
    helm:
      values: |-
        installCRDs: true
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions: [CreateNamespace=true]
    automated: { prune: true, selfHeal: true }

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: default
  annotations: { argocd.argoproj.io/sync-wave: "3" }
spec:
  acme:
    email: paludgnachmatteo.de@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory

    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - selector: {}
        http01: { ingress: { class: traefik } }
