apiVersion: v1
kind: Namespace
metadata: { name: contour }

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "1" }
spec:
  project: infrastructure
  source:
    chart: contour
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 10.0.0
    helm:
      values: |-
        globalArguments:
        contour:
          ingressClass:
            name: private
            default: true
        envoy:
          useHostPort: false
          service:
            type: ClusterIP
            externalTrafficPolicy: ''
            clusterIP: 10.43.0.100

  destination:
    namespace: contour
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions: [CreateNamespace=true]
    automated: { prune: true, selfHeal: true }
