apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: infrastructure
  source:
    chart: argocd-image-updater
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.8.1
    helm:
      values: |-
        extraArgs: ["--interval", "20s"]
        config:
          registries:
            - name: github container registry
              prefix: ghcr.io
              api_url: https://ghcr.io
              credentials: pullsecret:argocd/github-registry
              default: true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions: [CreateNamespace=true]
    automated: { prune: true, selfHeal: true }
