apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keel
  namespace: argocd
spec:
  project: infrastructure
  source:
    chart: keel
    repoURL: https://charts.keel.sh
    targetRevision: 0.9.11
    helm:
      values: |-
        image:
          repository: keelhq/keel
          tag: latest
          pullPolicy: Always
        helmProvider: { enabled: "false" }
        secret: { create: false }
        basicauth: { enabled: true }
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: { prune: true, selfHeal: true }
---
apiVersion: v1
kind: Service
metadata:
  name: keel
  namespace: kube-system
spec:
  selector: { app: keel }
  ports: [{ port: 9300, name: keel, targetPort: 9300 }]
