apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: infrastructure
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.4.0
    helm:
      values: |-
        defaultSettings:
          defaultReplicaCount: 1
          backupTarget: s3://longhorn-backup@us-east-1/
          backupTargetCredentialSecret: s3-secrets
        persistence: { defaultClass: false }
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  syncPolicy: { automated: { prune: true, selfHeal: true } }

---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  cron: "0 0 * * ?"
  task: "backup"
  groups: [default]
  retain: 5
  concurrency: 2

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
    kubernetes.io/ingress.class: traefik
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`longhorn.mp281x.xyz`)
      kind: Rule
      services: [{ name: longhorn-frontend, port: 80 }]
