
#? Cert Manager
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  annotations: { sealedsecrets.bitnami.com/cluster-wide: 'true' }
spec:
  encryptedData:
    api-token: AgAqGG7oCpW3OUMlzFAGBwwe2xP6OfgsQTG0IbBVY0lNf5ij8YwVnTwizary5DXoOr3U6U+uPx10vdnkxqVc6Eg6RgXY9wxeNgIzYVHoFCc4p9eMx5xJZl4svQ7mqzfdA/co5sIMtsmZSSpt25THx3Itz+d47YYTu9cYJ/yhum6Krd86cPmGbiH6vkUks1eLREUAyZfDiY9zHY6slluU0huYTazweh+LsXoJCbTYwpu9HqTsgTpi9z4vPDJSxJ62k+0rj6i7UNJVTxJjOhigp5WSiXytRtgUAM2QuLMhgMLfVAvMdoBxl67953thwmEEbUNJMMv1wlaH83GIYwkl/6M/0JIppbJFSwvXF/lSrEkeLRQFEy0mwc38JED6+HRLJFSFGyBGzgb5h8TLcqhzeO1/D7CsNiykM1ePVLkf4bPg8rld8t782jRRmsZXezQa/9E+l1Kuct1GMAn2XLGjV7UADRl7xthWFHNUUmCz1BT4LwvJNA0xaEpqtcOMtoB5NiQzFqk6oM7l6WGPlceDWYAb3NC6d+u00xGkI3kH+MzK0UsHByW6vTglICtscNaQlQ26VvnjOvU5mjeFiEYC8oIahLBu6CDY2vYgFXFi72N+iYpXByAgLGHSM00DS73bKIs8l3rileUVLL808wPPGOETwVXJjU8k2DZrVstTpdv0hJgwN2puG6K4OssuDJLKLQfsbEhkNwLhc5jiXkR8lg1NiNeaxaRjtSneaCZ0ZabRZNPmM160O8asqg==

---
#? Longhorn
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-secrets
  namespace: longhorn-system
  annotations: { sealedsecrets.bitnami.com/cluster-wide: 'true' }
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgALTm66nOFJbfuVO5FOUsLpUNzrIRjjq659G4Qt7/HqfSBCzt1VzJPYjKCQQjcnAVeXiMenFmWGqxiCRnoBkSkMf3yqz7OKBxApDexZ0nItqPpxj/6qtp1FlwnhrH1HADFNNjz4dH4SDHXGO6j7xsPOi0Nh8fC2AEz0K9ysJf4mHCFmTKYAoY9ZmTf7b3Q0rr1xVqGiP22CQdTP7RZVvaWq3sNtXgnsACClJDTaM+KHI4VE5Nd6/OOrZfOS8x5ekGvIo5nPnnvL33mWA7NXJf7xCxrnkNnYvgvF/OWj2JIqwMY4DsaDKcHynRwcamdQo9lX+54ohYPKWmY01PfidGeCw6/ZdJdqfSR9n2x+lFNR5+pNaVh+DA6YOl6eXRlBcYkXeWfsVxfpf7XsfEyhWAVCahj3RScNDBGO+sUJ8MnihA2fDpCY9HlpF9oftl+TNzu/un+6Umn7112Tv0rhifHUpITKCv8w1WPaGee8N2BFGDlu1Ya1zvXdjm7TkKC9kQmD2/d3YJRu9R59dyUOfQ4+zoCSumvbBgZC4ccsoNdhDFOJei2fGFywQZttzTZIYHGqTUEL7bbJkGY+ZiOpQam08a3pmwngFFOmZ70MK5w23KX4e2VyjMICF1By/hBKzjR9rhe5tiRAxu15HP57+2d4dmzNZ+27sOuPAjBCdLm/U0T4auuZ1eIPsNMfEg6/jDyURdB9kZyYAVIQtpyVbhoNXQg/m8mlQ+4vZ7CM+yzXGwk=
    AWS_SECRET_ACCESS_KEY: AgCYI1Ym4+/1jEp3dP8bauUl/SVQ9US7Z+oGGGy+LkpDCaxCmrMca/7lUknbpcTHbcCnEVBYna5HzYLQUUxfx193ZXB42jZLdx1CwrXe6sl1lBl6S0FR+fv0WhCTaYkGjWj/yXnDHKRcR24nq/kUPFvAu+o4kPMYfmU+/yxsoJVox4Aw0mpnacAMfE/ZdVD2zjTJgzaKm94tEj6JQon3uzZ26uvEWdNdEQjqJLn3fMu8idfJFtwNQPiBkwnK56j+EW8N1t41FjLiPcCKPeYoE3WRLn2qNi2+O/MJc4kWU8ixuvdRH0XxHQ15fTgq5L5wsGBr/bLn2USNQbCggv8OOb0ugKaQBiSXr/bSyYptHdqSB0H4lrsWUbMCthE1kf2SWnSJCTxPdn7wmEcLumy1pl21of1Z7cDJC4xVjfric+uWdOW0G5bom4s7LQvsZdOxVKfs/NqS3Pp2L3K2zRA+Bx9BCsHDTFTBRiXjtSOM8+L4oSUcA36laIcKOJx+kHqgTi62az3ZURFNoNhbYSIX/E29LqaHFxg3En11NxrbzKQHKRqJNP1EsGA+HMEmr7KuAyr1r0avwwyfPY2dmvU2jcdwoJ2FUsp8Jkx1ZgqvzriKwi3xCSdeWtfSV7Pd3XM0rHin2bJoMthab0Vi0axp/6y7n/cC5IgDB2mqKKZrkdI8f8OXrL6VA+aeuv9cPY2GbxMgTD2xF4EChGb3k68JYDhit78I/NIA/oWpY010C5srv+Y=
    AWS_ENDPOINTS: AgA9wkZgJKN/2jHxDZ3qkImzRy1Kqh03WFcVyN4C3S7SthCUpMxuigN/MAGZD+/ZCpTreRNA421Lv8AqQo7pP07H8MTKspPjNVvbVOy/gt2eENlliOZCr58LnZFkA6WiKQfKxrZdHd/2nQM2lqWVES50/Efi9kQS8pHXHzV88AN767Wb7tsEAhR54anYXejVFnDxadIFj7T1RdXO4MLzn6ix4f3Sqi8q5mvHJrEhBAcLZVsHGVDc8jUiV/GH9gBNajPCHTX/fXqqFSX8Z8MP1oz5jvfk55FLoXAxWCq0JyLwkAGFneLKvVKwnzjTNdQfKnvq0K7SgZNGalf4QS6Fh41w9E17eoWIo9uR0rRygvsu+Rrb86xAC3N5BMWZHMKf/VkEu3E4zexTvQ4zHKMrDxlfZX+y3Jlf80taGhqC43cuWEGx0kLEVL45fzjIylwpVFovP7Gu+uep7F3BSZwhuR7YSgePCwWqhLYDFL9aLesZGG1XyNZ8IfB3/cPcN9L7i2rwnVXHV3BDwklN+4zDKNDPAfoc6WdzzzPuxkT5zpIeu9gwDVxBIq3HXdB9AZSyRJB98OLkGKofdiW9jna1Sua8k/N5oS0TeyAfj4InEsjgm7gyiKSonmhSvqnlfoZl32gOsz1oTzTd+QDUJKHmigfCRw1X21p4micAFrft3sBRbXXE/YPWX6DTzwbcaNGaX8QlcxqV4+CtDHjMlEcAu7ES3sMHlReV16M34MiGrqs1

---
#? Tailscale
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale
  namespace: tailscale
  annotations: { sealedsecrets.bitnami.com/cluster-wide: 'true' }
spec:
  encryptedData:
    AUTH_KEY: AgBEO8fCspsQPeYPW8ic6HVrY/46TBMtC7f7vvXK7b+n/5hugHay/HIeDt3uENCAMq428IB6LR/Oh7zyaajTv8rDAfaoPY/INnLB2NYRLzuqqNB5fMBOj1t23CojWGkEfRtBcsIuj+H0ournGwAPtga7a9KxrW25RfAprMWuepS9El/PBxVNvB9nNMk6ydmg+BXGkypshAGpfynPbf1SZ+8BBxlKCbncYCxqUuVX2+kIn8tCDPKkoNKGm/ao+2CVgoAHWHTnEBB1NwQNuZBajBLbsUmr5EJqyh+6qIjzg0bdJs9SLS9Hq2Hcc93qdC0ymXKXr5ZIsuU99CdPutLm/wfOvD7uR1OrKEpzc6UkH0kXkQW+Ck5WdSdJ7Pgj9ROe1FMsrhe8t68e4wgMRSlI1ktgNo+XSgoO1b2rJElQMgXPFoMpLhZLqXVLKTPhW8o1rqEq/GA1RU49ClB1MMzPJEk19G4sKKZpaiY5zWs9ZEXkwjxzwgsoYRFqvYDywlZICUgAIMeUPKmix428BvAvLNS73Ee+OgNQPU5jJhQlDn0SucvQ0dYMiJEfMXXWz5QqW257NjSK7y9L3SUwCK4m9dLxE93EDQfaxxZezvxW1zrVnIeIWZiHGAYQfSQVmTeyyl0nPfAlaqFsuR2R8KBZH5A82tZCI6jPsKjm4QsOGhnmEuXXXuve4ne0LOtBYTVJg5/OsTyjU1hBAQkcbwEC8q2m6w99xDn8TWg39Kz+fZDGvaroqVknjQ9hW/Xf8EC4ul+eVM97kr4z1Tvg

