#? Cert Manager 
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    api-token: AgAUVgFzWr9d6n6P3E6WdnjbgjYSXYyZ+9uAbTwLlAINsKSO1WZW52YzGOYyi+GnQUUabR9O0aDHJPqu7ZA761AzLqb3srv4IEqbLi0izLKT+5U2MFSergG291F/MJyxBxLpl3TTdmQcD6KVVOQpcDH6t0AKUsYUoPAIuhmkfQSoAfruw9PAXqHQg5tAaV7VXgAaBzfjv3WowRWAQ34+6E3MpmPe5mAL82AG+AtMaOFdo65gwmVUqvwnLxyFcF3C95EwGyCIMoFEHVhMfgjj/psaugUWmhbhykvwQMU6DgI5n7QoZqf5/5bxBf9PUF9DR6/IT1Vdi4APjDuAE092+9UzIpQ1QnnlAo/R9aC0rY4hFuOX00GxPvC5EJYoo3JtdBCrEfIiaBeMuGHup8ajdNH7GgZY+AFhz4522Hnql/y7/RZSGTFVKM4mA1PMzF6ey9hkxrSPZjN70iPGEq4g5E9l6qezxjJOn+yFZMmtG1lamdSZzBaNiQHiRUEpi4efJGA7sZYKICWsSKU2oRJSiSKHjHYgPsr7PAojwt2fByHkKMFFkVaRZQufjlPP5yVCJ9Cm/afabVFi6CrUislu5Dq/ZJZCrMzMeatZWciklhJdnomFth52/rC6j1K6vr1Olu54B1IxvIyVApsS8wAxd9S9sLHRWpPlRGUy82UOVyCdI78e1J0tgy7974CYtnaJTeaQHwKJlSaQ8khrBgGryAWFTnq4xjGD4oIpd9SCA1hw2841URLe5cWb

---
#? Longhorn
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-secrets
  namespace: longhorn-system
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBx9i0Z50nnX29TPYv5xh6QXwUmVgnbww3u+NhI126yxnQC5urNalg/cHBXsNbzWj5xPSHc3T24Mf1i4MR3VdVGDVKnrwgtXiZjTIgTiS/z//lfZb3GNCJYQ5XQRRVGq0v3bHvWWqPnqvMsRjLdV0CpkBQW9Z8OIEJKPor5Z2Yff6KJBn05gxUBrD/Po9a/+d4fcSs7H3vSZefsSRoTQBONtDfpqiwaAKZvPMOi0JB8Wy+QrRNLWX1kSDxAVqYICBUQ1JrFPUU/P4T8JWcI5qE2nsimGodQZ32EqD9k4tcvHdfFxfpr2XerdH1MapqPa01UPHDhoJMt5kxHe+gvBX/7QBhitKG7Mct0FqjDIw6zwtETot8/gYydHTplYjpXNj6O4OkRVg4B7oqHwyZGZg6PV2Fqg3bDF7jgt3Zckles3JEm1+6keZ5iDDlhjOTo6jKlqhNlcOwfl1j/socVuzDpZiul9ljmbPC3TdMdYG2jJm7lAWTso6OFnbfkvL/VtxiQjYugYNB5wa7bRW5yG6qx6xo2TrzzWbMyNcq0HHR5BZxE1T/n6ZeGW5lbDCG9+2/iXCz6OlWjsMJ7g+xu6Ew1SpT76rIbsXfdUZNT6uLaGCVkXW0zDQOcCSdsu0L9WnigZTPzoF8ImnUwe4PGqffM0whElncoBn7E8uGYUX3cPhpDomJEsVnNi/YqIpi9u1VN1k59hbqR0yhMZkQ74DdBwi2zRnP3xaZyxEYVCpIZyw==
    AWS_SECRET_ACCESS_KEY: AgAio9qk1m5MX+Dl+wEFCrK5DnT9OUp3C4P7WjbKUGf1mMiCbWwgvJXJCR2Xj4j8F32mrQNryfiyV/Fk5T3+CuvlxU376jxgJgz29ZryuRERuQ4b8xrIlI+D5eGTinqQKDf3fkMuEg35AepxfYx0rJc2yxnhM61+nia8Wu3IyZQUg2/LHi0wusSmXu+CapDB9EWdKCHc1uUhuxaHrHNZ+JPHfVDtrnDDrWESsu6qUh1r9lHMU06GV7dXyXHa8R2bFkIwSfOar6Gz5Ca++GK/bTIptEmUyIOiaMwwvVbjljxcGzv4I6hhOHmupqvOnmieq8/oogRnWoMZWcXeNj4GW74vfNhwMZjbyZOKRI1DSSHI0tjyugqm9Uz140FHoryuv+zET1kkTdXIb8XOzJEqPzVxJXAyMdvZZfBxMZsmcoMnFaULde/KolH40Pbup6+E69ckEdwKadocaMFXG6vwoFokOBIJUo3odTk23W8vz4YSQWh9lXytSxYKd3mHGluHRqBH9dau0GWASLAxzToxeY79ZkGu3jrtHXsmuwpfmA21+k9XU0s1+UXiMajP8WkhMMsmlBEAmYG8JpLOWhQHpkWgxayKaVeUDn7jEIgyeB+lDDfScqOgC8TPFvQ9Q9bVW0DmLNl9I1fBgRAFeR7GXnIaCLugF4yalOLi9WdL1poFYrtL1GyKISkdmlQD8U5IOkQpxo8zkZ1rm24bEf93HpXRpiWedwQOKHUuzVwhwihBYg==
    AWS_ENDPOINTS: AgAbeh9MJnrLXKrU3SUqIpWrGORNeK49yEu3QYy4qGjIDW1HMypumoWiZ/t5E7voeu/vWv7ExSEVk2jb/0cDfMM8+2KBBjkY82b1STQq8y8a2txt3oq5YwHaZrjeuiBaRY8JeULsqcgPM/2aIfxsJ33/9/WdFdK0pF5+f767hAs1OKdYg/FkEHel4feDweAQbpMXfdtqzTqJSUxudtqk1iARc8NJ5/68ni15Ns1qiVJgJbXDYPdTK0Y4Q3sUbb2H3ULcfClj4dec4Cf5frubLk44n3gM/kSS3doZkLRsy35aztc/htmQ3DkMhMUDYNP1nHet3C3f+jxWvq8k/ajcS+DcbfRf6QPYR7jbNFmWmnJ76OU+kgRHoE3VEwVEOrqm6Xid2rX8aYVyYLTUj9beL3IzlWDFaq+xB/Hot/mnGhyWTYkfCLhpi9FUv9IYUUFl4a2TBCIymmni2GCRaY7gK0CI+B8dN5U88S/DfIOfwBqeWBdCGv4+Mf7cU7yRtpQ1szmN7N6WAgDDhgtrDaRNX+YsGyGdSPMb0eYK3bD8xDF0cPqZjmxWdUzVoSWb45NCBEd2+oZWRT7Ro/tAuq+7DmUqGmCRwbFYnm3sBBxfh1W4j0+tSvzgOxcVmPooZBg7rpbTQiMRSjUZkYEikE3sIk//PJ1BdOLW0nQ9FteVtWXyngbeZj00uGyIeyH+acgxs3vuAMtNxIvEU8BIIOr9w1jKtpXhvMBWNl1Z9bNTGTQ=

---
#? Tailscale
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale
  namespace: tailscale
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    AUTH_KEY: AgAcUoAkB1JmdZ77iM2PgdNONMER07VQIv96l1+bSsUApAeIa7X5nvqGpz7F5114zhNjsVbFldrUzjC2kbHhETJQHw3TdLnMX3JIno1PYjsfwwVadhpR1aGicXqzquyWpDOAMST9m833abMLK2JnGEk1PlSrzvytjLPSf/xAzByYQHZ2IpupjHeD7mm5qpLr9ae13Tuo9S4Uuq7V856iikAlf6fNhPDMxYYdzN7fv2Nf42ZKRWboq7fcA2SdGZ6eZ54pMSMyUE6uDic4cgZN0gcAu7GIe8qpkEbvNM58G0Bzo+R5PLbMfm4fWsEZE/6B/qEZnYgOHs5Z6amzTL0yS0oyifpRAj+R2K+En8RYbo+o0IXh7RRMa+muPEfv+G0288t2XObXgRJpyQdZcEDIXFvmbBcJzmymHv0c91H4l4917CdGhVIqzt/uUbYzh6XU+N7d/T2XoqBzPQ/jZRhgJzmyq0x3Uy0TxWBZb/Wvp12aQQoTmfmpzBYTSlWRZrGsO7dQKCuJCggC7q21qapD6WomnxiiqtX+TdxpowOmpS0chAj6DNCQGQX4XX/2TMezw52TYfctfwVIpNmN/Pwqkj15QYSHAhjxMsvyf49yOmlQzbe7DA3MwN70Wpd9ApUTO2ufY16DH+THCHFujFIYtC6EVjJ9S9zUB7/NicKZmr/KXup+pry64DA1n+PqJjF9JfwrDc12PHqkp0EnIDpGGvUeQMLSAuwjj7trBUTJa0FqxUBgLLBybTiSufpgjN1cr5HMt7701LT3vfg=

