#? Cert Manager 
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    api-token: AgAe9tiRaGVT557WHPjJ5HoQqqfB9lzYYoBfvOcalud+lWQ5E8paEAFyJPx+XCdWCicXdCVa0ESrlU/vdnIXn0pkVOZIAYlPhfFRy5R2/UftMrQv8yndVshnUkkEm5kV79IGhoWEWjRPAx5e67spYaMcn7Vct6p6m/tSPZFRW3SllmynOJaAEH5ijh2aRYANkak0mdT5J2vVcR+o2wDEE8SmA7NpNcAFxNMkz9DVUpVamwNIgMiKhLqc3MWKlp5HqPceX4LJdQ9uGChz9Xjb0KVIfQTDDE2rqQUsn+Hf6o3U+BcCkzF4QEHoRZfdZdHgbz3rY5e6GplQRgcmxXszqP+ev8CB1/4LpSui/vZf9P+qU+4TicH4IfsQX6vl9MVLN8wIN2bsI9ePlLzRSUXCEA66o07/ix8pkbZin6EDsBlbVPyNFhxl7U77I4232Lcnz75hOmbOH+S+QATRRHe81SkICgIwPa26R09+nKk18O3Kf+5hqg+f/ZjlmJ04pT/knK0RAxf8fpcSwxpo2orgzRAWWwtKbqZDPJ4DImxmrpNaNwjpV2KvRF7fcE45if+9RGnT57wY040L4EH7A8iDRmrJlOcKM6qNgcfwX28BqnmY1qy+lAOH2O/XHESK/4LkwfPTFmTQ0/I975WraQ6kEVLZ4PhwSdRhI972hqcWq/2ntadwJSA9spgq+gyOnUTbUxJyCufRopu1D5QY9WGZsefpnvLntHqE0e32zvfeBuI3qjmD8o+HUnJy

---
#? Longhorn
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-secrets
  namespace: longhorn-system
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgA890ELK0waj4fF6CiLJpezlZM7SxQyegfDRGpeUBe8DljNnPkr7ePJ+ngmSLuaL3BynDe7sAey/APpYvoXA4cY+fwWpMPVrTEeM5oaTWeIrUoFjkeITHjR7Nzl4XzotFex4I6Bspv4qAdYxQaHyf8Ugw19zeewwZnWCECluBXX7BLbBc/nE5G6nvVqTFWmxseqhLgW8SPPu0XenkckYZJbeZJHkvQmSz3x1Id5y/kM0tWcsaL+5VuPjnlbFl7tR6JQVi6h6LGkHsg6yGyRJwTfCZtYBZN4qyDDdD/fYRmqLTvOpyoLgAMt0QVW8WM+Eo69sRVA+2X0MoWlTtJdHCuFcAbo/Ah4VY8gw8J1MwgIKpE6lh5OEw4QlAMmFxzy/fEDYJQRrgzdID5+Ch75ZCD2vGCKhLvZdQ9ssb17IXAepFFFKcT8H+XTZbGUBbf7zLPBoHTo31dSsynSB0xzbfzqoYZNfOMt8LvJ7mNIXAjzQrkwrKSs3UsSz+acEaOY6IBgIl7wshaVlXhDcxCv5heQonm2ibzxZ8nLINp9octIm7NbbUKYRhjvKbd2BeQCJXZhLo3Wi2e+7uHekZ64PWJQgYmsZhW1R7c1cmOu7MGC+2v18rPLwKSYYvWFge+Gf6jSVShEydTO0LToagUBXrO/cTLrK5s9bwYgiM/xXRsg9RujD8KPGrIM2aPFM1Rdx7C6ONR5iR4NdW1Xm/tQhIP8CoaE1aZOAT4tBIOX7yveAw==
    AWS_SECRET_ACCESS_KEY: AgBQRl9BpP06hHnERAd4VqYi2ztMEvgR4smaAdxC0/yURAW14li6q7TAyFgDf+LRDYjbL/9U44ZIdoCWPBBpC5ZbJmuzb494fpz9A186spN0rlchtthqEkcK0TFkrKaHyN8YZM7vTJKWtXz8STMcn4KP6y4eT18DaH+02wkjmeTgXHoXrRx96dip6L6GDD3XBqfCYXBJoAFTTVWjE6oq/LLd6aZgvXA6QGITGdrIQqj6R/V5dqNkjCz9JRlB/5G/3//jY424V2g49xcayfe53zDHTh5ibfdjNabAZoBHxm/BpRCWqKsj9ca0lcaNYHX2ciCZg73tVMwvca1U1Hex/MI6F+UoYdrd9LrP6/+uBGXdzfNK0qkCxwqK+a288DUEvsS7dMo9q/S2myRblOaKH1aqN9N36OYmBx+hfnLd3jyZT4GqmjBARAHBZKOoypWe5xXJBn61itB+Tex8H3EOvhR4iNQA4zdj+IFaY60CvnXrnrQwvZOowcl8wQeC428G44VhBnHvTRLcefsFG1jLtNuaWxIHLEj89VMv7XLrOZJofLYq0mTohRrNtv5om70SihQQzKOZ2LcEIKeuxNn3c3EvmyyKXmNtXtKZgeF6qhG3EGynTxOZcMSgQFrRXOelGo/QpQqJDMliTDm7wncSi9RWkWjOVBotQN/g1RTt/Z6nL9eWfSwk0Ry3ILZtR0wd7AmSqc+QZkaw2KZzib6yKa/5O1yQOE9d5nhKWfTMbXbDYw==
    AWS_ENDPOINTS: AgBUq+N2amB4K+HLIJfeB7LOr5GFDEneMjUiN/w/DQXMVPTy0Qt0KTUK//z/Nszxb92tGUVlopBtTm+W5X3rcnMNKPMPkkrTC9fdjM6GMrYL3lIhitB+nGWlCd4uUnl0/uiU4ZSBYbUsznxAOYun21ox7CpNu836vCvDOidMnJPefF/HI+phJw4NlukV56qzuP+R2HjfYAABXQHreXdmgmhYxNP3e9OwVfv8yZnl184iT8Z3H6OJt2ywSQgyq4RBmKUq1bkMLOJ2D1kZ0FNUf5gfjAMsYg1LmuzywzjyG2kugNAQa+72A3ok7mkKxgKYvxH6fHrDB5ggy0TBEBkYT9Iox8VexXxGTgEDgWzkIt+wjB6VrQHgaJB0PzK6cDkqZzTPK1eVmxkag2vbODix204EE8tHM56IH/D+gcYCarEXsFwSIXe09aVwWnsAdjaVPisY6OKZ6ozXwet8M9xAkt6/DZMQQbX8RKutU5MgjPldzWE+FEVYJRu/04SvyEoxmjBEWdczevTF99DrqTOdw9om+QBOGe/yY9InTdenyfrV2njSIJL7SxNs3xvvCKpyzdrKPgONJjcHZPDmFzOUSbolNw4LZN7lvjNhliC5MeP7K8DJoCwnU6vR/eQblkDaVb17LNzqQ4kuEj7UJG3Gbzf17XebVgpC84+0DxJkpEnaEn8Ts5ZpM82/OSyFGDxPxaws8zEx7iUl906HdNP1EaCNjZxezGJTo4FqFGLv0uc=

---
#? Tailscale
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale
  namespace: tailscale
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    AUTH_KEY: AgB9BKSWSHojwmOALJP7Ev5xcOF/tRglnHhUQex611/Ogx/KsrZvtfyhBgQMiDYZ2VTo/ZyS5Qoiy/T3wCJkuAEBpIh43zK/fBHqcDpXfgbPelAfw+LxsPlQG/RnxkQKoEsKUoSuubGriyzRSCVKxZYFxRlNMMOUHBZuDjPJTrCSbu/dWD7ZHC3zjVsZqAU8jx6Et0pYGD4pPxmNVXB0Y8WjuhDdGaVncTfUH3ZZt0vEe16z17L/mKpOTVmflDDZHkHrHd0Y56vI8WQM2Mu3cVYk6JBca5OpgmdxGeR/tCTkBsSbGJrooGNhi4SCxk4LDlErSRFl5+ylOkbkSP7jbtDjN0pgXIX6AgRW1U1HrERrPyvszaCZs342PYUmS/Nr0dtpRTcaOKvSPMj3WoldCUoenWcYYlgGlQT8yh8Nl+vhSq71nNi+a1A+JNIUa25TpodM0HTHHPAp3CA5PALl3/7Ntu9BBtf4c+x7i2zLLEYCcAKDEwXcR0gqcmIdQ/8GHq01ukXYO1zhKznxpJg8ysG4NFTiVlVm6Zxjl9NjZQhCeF5zbn6DHGmWqtrsDn40xkBV6Vfq3liOheQCxxpumL3ArcfXSB003O6m/8LlVwufRJFj+lmyzraL87fNi//JBlHB2piKnuYR7+azN5ipM5pmWBM6JpstWImuDp4CDPAcH6dbMW32Z6JTD3fDne13cj8XGNyWCFD7xydp7d9uACXzrY8K3WZRb4pRMS7JqRsl+Tc8Y34OmxzAb67/EGC3/Vqq1Y0iJ6NgBlg=

---
#? Kaniko 
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github_token
  namespace: kaniko
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    github_token: AgAYlUnseEoPDmjfN+LiSbvA/P/Vs38tax0oOpbE2APx9kiZiIUMpIw4BnDW2KhXosGsky3Rw72oE0FzfL3t+OHZAbWVY2HBxWItqNjSS3mLnMh/h4AwqW97YxX+eQejbMDO/B7bGkca8dXEsp7BJBoxhiuB/rnsk4GWtOKkXbDKXE1MeDrf5FIpA/UK6vgHQn3/EpoPVqQc7tJ7HJgtGXb9+SAhmaLvkFh6EMfhIkmXQvEmqr+j5AqCGcs7qxEpE589Uq67bvIZ3Kqk1uQTkQ9Yrfqzb+ECcfyEbiL9q604gYveUJ6WWdfk38nl0wKn7UwUNDJFB7SMvkMYGC8T8+i7OFSYHyZ45t8hYU1Q3qnDVxJPMyZhm4spGNX0LOoalvxP+bjvyckz3U4R2COK35ZfTIax1HWuN7QVsCw9Yt8cLCtQ58U0M+BjhKhgeH/EV9PSztvE5gKymxD6JAa/PsylcjSzEtyrMjuSSJuhPxIqOmqvn59XmkggkAIO3howPPRqySYrTI3VpSAW/GeTnsj/LbqogCZA3M4j6k/+D5S9v9OErxiPhCznbIrsYwhBWacnYRBxtNYnvndhlg/qD0TXG7uhHgL+Dp+aL97V0tNSC5A52GQlcwZuKQTjYYyGClI2qCmnFm8aiDRp8eqPLH4s3L8d0h/e515UXrOl/E7FOQbh7yZ8s5N35CKJ4mAU2io+CePXhopyTtFSfPlR9CtMhbup8xrUx6FtCU1wcDRAmWGFfFJKD8ST
