
#? Cert Manager
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  annotations: { sealedsecrets.bitnami.com/cluster-wide: 'true' }
spec:
  encryptedData:
    api-token: AgBmNJuS/CZJSxhHG8bpW6C4dHWnfyULd9SmhjbcQQFJcf1fQWckjNkGaRqzMl8Y+lnRHun0qyIfBuqyL3VOm5U3+fFTro8l/2s1/aLPxa3Mqvm59GiEaSfKEkOCVWJ2gPboH/vzZjSyVIuFivkY9WddXyGCibVTqUrRmjQny66TEjZkR73q5cX96u3MHQ1Qd/y0lw0Uqe8dlCT6aIY20gFRxPyfqaWb74fSVImJ9I+mS2f0XAAJNjG3vvAX9QcHHQ6K5p4zQB1rZWL8zkiWb3OSMBZFXU4a4Jq4yTUUgF/W2Pu8OwSGxcy81x76AROxgtFaFfu3RFUtZOxqYw5x9EOAeXuOFLt+9QYebWTXTCw2R1UzRk8I+CQ1yBJiboGalclEtWsCdnqW5etFKiegUa/AcIFA3rsvIS4PgllgCiCVEuI+YG7alE+JLLMexILxj+a22rZpUqQWz8WnnLHPIMzfkM1FYwTkpaO/greutGdEJWVWf42DSNcoysW1dylvpQdTlhLoGYKAOj8sfscjIwmdY+FBjqCWBGswyoDcLZ1UvuHeTTPxEodVADG4Mo7hnHW1NdW5ewwtDrpsIb8sSoa8OxdQikXalt1l0T4WRFbiRe232LyhlkTkf7hJEZeifBa33MIUZf7wYYQFy5A1YKJz3wAGZFcuH147M59DI7sPLl0siy0QUtpHSXSQCpOdgBMqeP1snK0xVUOZmto7MujO1OHBVU7xSzpNojSvPc4NNGf8fF4dbipk

---
#? Longhorn
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-secrets
  namespace: longhorn-system
  annotations: { sealedsecrets.bitnami.com/cluster-wide: 'true' }
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgALWkuX6xSvP6jtf4htie5G2RRb8132g4jBwvqJ4Wdyap4/pgzV/zz3eGJVIFIQi1TZ9FXfKCRBC6mbNdoJ5KiTxaVuxbRE2hxVjXpg3XL4r8YDZ2YgxUKy47kg51rscuuOLtfqStc67wdwEcxePXl2Qj6M/Si6NFZJiyVpgf3MUqzq9X4oh80pQEYpBpVGDd/5xs7XL9Sw/ZeqnWVMDyGOYtMq1YSeDsDsVN9mfQtfZnPZ68Qpp6DKO8nCMpapYJ4WdRq/Fsms8JrjJyGQzmWTG8SrGRuz18Tg0XysXA/ObrXagnlwFFkGJWt1lSmD2O4gr/rWcxs/jrYW1RtBOx0XQtln0SKDXrlJLdbs2A8QHY+GsmGuPuf4IeCwqekGXlLsyTZifot+P2ILSwtkLVOOXSWAK5ULSKFA44Zbf94FdSqqm0PmqPALavlz4wsBFIFNcm7SXo//yIOypFTelnY5YRQq30oEKBvIyQXlwHYOb6pc6a/LYqJK0rxPulduKitqsddOJ2/hdK2KO7ZFA/d978GzHfLOBbQTYFXO+JiN8iiKyIIKWygyWAulc85dZ1YxXzjFYuF2U8IYsaehEWom5WkX9N69PLHhQemBFK71zYV+aXfUkiRQ/0gTXJ/vh4po+O++y86PCXHFh3ugsJ3Zca8P+BrWVdYQrXcfVPePiWCa45zHHgDMTOkGf9xS0YWAMlvdj0dReqxooMM24E/BoYU6Fjg53AjVx2IF/vECKw==
    AWS_SECRET_ACCESS_KEY: AgAmJ8/fS0jXx8uqFSyq5x7Ir5QOKTKuzC6Xcgo50gACNLgfO4wtSS1IlXCfngKR3BG/iVfosFrE1iQFxxbkuq0FLMDHc159hcZOAxbU8cLD10jHK5C6a32DNdB+jbO9USF+DVh/nHZcOASSHYrG3lflLr571St7MKBC8CUqD5agFLKzFNzVqi3/BZ7WITqTHvRCp2qgUABgq6rMazOVgVZW8gsl0nKaairIjSDjXLgEwS28DYWnAndjb6XEOPCSQYp2JaAagGVT0tXxgv8SEtRv5F8dqZs8pNBGhmJ6fbSbpn+FkdfZgvXdWFv8/LoMWMUtbMwq2ghfDytJWFYoKmbG9MhvPocdDzEdXRa2ZaXdqX0uaOX2Yi98NRqQl83W91KPlyzU0mVvJvac3utJsSsg8GbDQd2qUGBZjn7tRVD6D1bf4Hf9QAZkh/1bRNIyZ6mvISqhVBTzCm9S34WOLL/EyH6WkynDGRLCAEoj0k3vyosXsqxJIi/LDVDhrWWgwcM3f4nCkRZ0dMyWGZXiMzV7i6XSPGw3INJASiXy1MwnDMUdbb4Y9T1LczJVMybzCsBhqh69TOnPvqqg084kRc8G9+ZGmkcuVSSa2pD/Gu3A/CokfWhk4hhG3Uqf3pDzT5meHoR4rU3y9EEvrWW/tcTE2WcoLtRma2lW3/TZfAC/UQvA+N+IacKS2b0tBfSg815kFYb079pWKZgAC/oO69mEjNKhpz+0yuxqtEEZfjeW5Q==
    AWS_ENDPOINTS: AgBqNOm/29rYKyMCB52qFOG7+WdLUZmKc8WMVuCGSKC6hgs1AFTBRge5C5Coc/nSUKQLqetdLzMWocek2fHKLLcnZzQKPRiWiJyhHm8Oc3mXOtPK77scMx+VTasN5Cj+Zg60FXcIpVUEj26Br/Wu99Pi0cZbkumN3NMDLBOuJeHjgqcD4CdCxmAcVPP2/gDF7wjDma07maqoCd8HlDKt8MltaynRMYYWwJjimjpGeAHNE2Ql+zZWwb2SYyvwpj1iPG+LzUcTFVNS1tYS1vF9jFA4I36ic7ZCtcx1UCvAQAov/5Ma3dsvVSsRrqcvAN6j7wNGeRQITB6DnAOL5QIpwX4ZsnOoknhyfwH7CxRNg6NaRwyRmdN3HmStR979B7M8rba+JlwpT9rdkYUZxILwTUaTXdDU9yopnXOELumPUVUk1u3KfHS0BtKVKKtoRFKLXdrPBboPMmGRxWHtm3yLmyK6jNhAcp1WVoerG1sPa1WIG3/+i+uGzv6S64R+tpCj6peXEQtYke3zKuYGAWsqznPSj7OOF1WKGAiOJ3Sb75eMcNA9xPO74U3LNoKGjR7kdOXfTxhruB3eYO7xHdQ+onG/rFPwS9czBoSsKi+5ALALsOxIQTzjtfqIbb8al79YyWBKLN42Pud7m7H0IHIxMPqOoddtbE9y+bDeBI33B/ekbMPfyoDB+/7GXFHkKozqo9IDm/TLPfT7lTViUKIiVEM7DjhsuU/VKBwgvOKE1fI=

---
#? Tailscale
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale
  namespace: tailscale
  annotations: { sealedsecrets.bitnami.com/cluster-wide: 'true' }
spec:
  encryptedData:
    AUTH_KEY: AgAW8g9XBVkcfYTh7Yy5ti4PuEkQORJ/6pYPyXxy5zO2aS8fnnGJRkC+8VW8KhtCTc88/Gut/nOVjzXe4NumnIAN6+k5HtOA8O0IDHq0ni8feiJCAflq56n4np/UeWslExV8Y26pC6Syd4xx42eOYGhHX1Qv41krTD5I6VZUvR+SbqDecnFxU8lQNzdeZjIdNtcPqpuvlT5suJgfXpvKFZGc6oy/jZLJcyxeHlF0J+4DGZ4q3MonIEVzrq3bMuHhR/LYSEUk9XSaRdtVhmD6oP6CPEkUSoE6AQhLTDYk5AgV4MVKaWS+0kW/6GZK/kfBSk6jwm9E0HqnvViHiFpKhQ12l6XTg61pYESmbpS6EUNS5/x0NO4swOhSZU0jGjHuYZgU/LHrnBVHUi/K3voD2MY5C+8nLp5YgJE0b6Vgre+3eg3PWwAnFGiWSDMm612lWiCTCFoQ1FCMzdNv0jAXI6Eme6PbjIoDrgyKEWSIPFPAke755YrWs0bk10pS/yY+TEnZwSYvI4DHM96j0GdhDrt3Zniw1UW9I/V8Zt1v3pdoxh2MA7m4r8oV7NWVyarm0OguAnNSrRivUY4KpY9FW7OW+DuL8gluyyS2yF1x0tFjKFBKrd2lUUI5/jDxHSCUqA5Djvoy9WVyADIgEGvU27MH6LawnAgBGm1bCsyMSYWIhBSFuzVWUVbeeOhIUFndEVk00W+4BI0y+EOuRbx1kAzZvt6eUZtITZD0u5vCp+z25RJbpMqQVGCnaA9dQCXEGbDEl5sbqvAiVYc=

