
#? Cert Manager
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  annotations: { sealedsecrets.bitnami.com/cluster-wide: 'true' }
spec:
  encryptedData:
    api-token: AgBj3H9lwD/5S+hipFrxJigv4CwUw3ZDqPc+qO/1tN9si84DNUFxeJoMDox/A9k+FisCmhANiupun02fMre/6UTsKy5z49+ajyVOSSnlrE/QH/fIwcrOskPINwEhtRAnCULTqmH8VfwbgF6qApucgpV/oDc2sO1sD6d8vSmxB1ODcisW75hHSrIC0GkAay047uoCSPZ+SM92MhWs1RSDH+kPc/RlPBpDFMOg3Cu8fvL5R9r0WqbihT7ugBmcHCem/ywROHVrbIJ8ggCpzfa3UDgzmUh+ZL2nlb1uh5N26daczHI3ueFYGV8OYhLOixEnoFExVkGgpemcQR2VcKtPIt2kDdsr/TJC0GWBw+iPpLCiYdlUfmrqwYZFH00J9H3T2igJKXzE3Wx+td4EzhluVs1Ya7/89pATz8jpXQ+ecGq6XEy6wMenPBhlYHwdyTZmShddQj9+ji1JxivkSSRhGG4fMg3B3Hz984mxWTU1OLHA6007+DtRlQ+2SH5Dm+TiPYAtejdLyzwfY2KRDzv4Gl9NaSYYItusFr4o+BR/LwNExQl5RYRtv8POhMeUasWrtEnZxZHhbRnMRQ+/QC3Xr3vmlQ1GwegN8xj1x8kjQIhWD0AWS6O7e0lbwZk6M4aetYEPU1bDgN2cHmTvpmwAy6f964akzu5RHF8heIAytQuLj6zvxM42gqcACVh3EfJDncjymF0nKRb9kyH677yZdgnnqs0Jj9MKJdtrVgciUc+C6kWtTfiUSerg

---
#? Longhorn
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-secrets
  namespace: longhorn-system
  annotations: { sealedsecrets.bitnami.com/cluster-wide: 'true' }
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgDR69HUYvJPHtcRLOk7zTwcG683UdUideHNQZfnH9n4JC6IeA069MiAnn+7ynPqIUP6m2cmv4piEHbt5kY/dsuwKry253qx9KXL74jPznWa3CufwVF+8wg+nB6I8FZ4BGHRrIth3Ntlm789Vf9s88rI/CtrzMVV+W8W+jgqPD5XKGgTW9JIg/rxkpeaVvhFSohvTh7lvioi2TCgJQGlxKB70tm7A84oa2RyTcQWy766LQPG82+GjUTHpvVptB55diwp0R7I3NMi9Ws2SmRCmoQegRbQ+9Nf5Q39pmoURfaVhZlTMleyFGMKnxiqwhU503vNA+RbvrgVWBjMj0nYmDMWfOY5h5TGe9w0CwpfIbPEkkK5WMrMgrVkUFWOoz1eVaxjN+LCBUT1huHa2AtDYXhKgf0/BjzbeMAWhIgKG3oXF7CEEPlw4g+cusT/uUA9ukn0JjsjIWg/3b/ewq5Csb5cmT05wUyJtA/JJ5/s0wq11eWkLMUGOZaN6XWO9DgNWiz/gG/2NwR89pJogXz3y6dMP9ElQxsxQvvB3AjoRNLYbeYblEP2phdMgJjSFb0NhyGK1YjxROFCUpHoTOMOL/MXTwXkn/A8guS/dbfEFgWSf4bx+eTW6X+GsRRo9z+bVkSdgeaTW7xNMMVDfkKcPO3HY9bN/mUOYoKL+5gQT/95vDhO6Alajk397H6348D8B7aOIX+YSdK767wSaRoo2jiXF7xgD6phimvV3bAwVULJHw==
    AWS_SECRET_ACCESS_KEY: AgBSY1lSFNPc4npk6Kmx/YdiOsVzlnFWo7wV1hPlX3ix3uxzOc8Ecd0Ym5Wq5GaFM26yrC9z+Je201/gZhQlTOECnu48J+kMPPLE5ZtzfV+f3YvbUXxc4K6xcjtiz39h/QWQL4s3/ZYKtiUzQOZz5v9cBw2CLiU4+k5v1ZaN8EhNViK0Fr133/bs6E2VlMB/CEgnKCADRgVXlHf3I46zYsZ0NNYwP/rpZLrQfg2+uqnvB0FhUCJuYdM9TuhJMFTRYGMqEDCNWLy4XSZCNgK6EXdj1ETXACWUw2L/RWWUk6JHlnxeWs1E0j4EAvIKaO74oG8fFrZE3crTTqA/LOZDe39eud6r0PfwPE/yg6ewLzZp+EgFMz39c4RGHZhqdC1pzcOgiCdQGBWUn5we5FzEVMFlb25sipo6RgTplSdMUuzVZX7pyEYEoIpq7omP6xP8Sdi6Zk2kNkgPnHLUuF6wXFBmToVcOMwGIJs+aAPf+8T5Naops6Dr5lZc16Exnq1FKi8nudYcTyV1qVRpIRUA9H048q7iijd4mLo06dNoKsp41SzGuZLWJLEIj1BxbTr1TKlO5T/e281yUMVbI/LltlUsBIhoLW//pZX/HnFIaAZxfkyrztO/TdgqkKnaPIgNsYoZDQ1ZU/hmnojooJfsVqdatD1AoMNumv05vHT6PIBf12jjEPWmKqAMI6xHSJAbLhcWORTGjlD6KcMSSMJEgEWwo90/Y8BwWbjV6Ov3hEQCeQ==
    AWS_ENDPOINTS: AgC+9HxEO+uofNoUEYBtFwGeZJ6c90dPQ7CC4DfLgkMEBeL8eQlRjOIbcR/A72I/p6olJp4fmSlrARvohiag6qI7GCAxNfT0eGQhM1fSsqavBNeL5x0N0/medwzgk48QuJNPPd6HJRCBB1v1OACNHTfAqb/awGYxECQz1t81XKbV1Mu7hwDfB9oh8Zukj71eSWhyOrdE+fPnvSgRfd66hf2OegqXjZJ3DrYQpGxYkOzNmokh4b+5REQAI6MBEdxYOx15Nlcb98EFfeoLcF7kFRgEp+b3huMu6fhcXNHaQNORbN9rriYk7onPrE1wrLkSjcB3MchmjiotCFIYSXWGPGMkGon3mzXu4Dlluru7cBjWPdsVS/Qm+rzqM58iWSy0EFZjPxs0iQmIE8g5ewdC0B8djFTGtfAwI5bi1Wwn4OeyK8GhdeFHf8gmPZaHdpMcTb8+41uez8at7MkMY9DOGIcuKVPjr/cdv8KgsExoSWKi1ZPZb64HV8JO91DbLKZEtbIfk9OEBaxdjSgPCR5IOvM39mCdRpccIPZHcrMVdWl8ZHSAJNQgUgXgJWau4460jqUidVfflx7S4SO9WT4koZTVZjg42xymmusJWO/ovtJsJ54874G91gn7KooCX1a/X2KuE1kTk4z6pSv3T9t6gqRa3W/jnE4IyYu1pobMXWODiRzkB8rQLTL+n30HVpkS9K4FfI48CqJRko2dOKi8Srm6cxVtNzJYgcRXzg4N3+I=

---
#? Tailscale
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale
  namespace: tailscale
  annotations: { sealedsecrets.bitnami.com/cluster-wide: 'true' }
spec:
  encryptedData:
    AUTH_KEY: AgA2/ZAsrUvLXYGmIffcEMy0FlE9umhyMi8dWQBEAYEndtk+P0evrws58AaduOjv2R4auomXIbYYRNztWM1ikF5U/1wUDeAaidU79WlobIdBH1W+wv5hdb5C6MKdlKXQU9GeQH1RiJN1J7lhxdyHJWSlaIJacZw16CmNBomwusL4yaxrmmwB/mpxGGKRk+ib2/X+72dUjkIZR9A9SW3st1R4hguBUlLdOdoEY/daoF0f8iblerZzGadc8/np97b7lqY6rDUA0Fgg/BRzHpSJYIi3NEmD0ZikAWumaDXuKl/LucN/IiOUAo5PJQW7ibcASM/5Z59PZmPpSpi3n1haQEVwDjjHyqVf3Q0txh/8rPGy2Z0K6ztCyLv96J17em2QlJ6dq7gXtmkTkrEukOf/nTzsr/nwZPSdjTCuoIoZLxUjz48lm9qOW1jCB+SgqJx28lQgr2RC6rBWeqXY81Rtdkp+QvFELhOcHLM6tASp3ZJRisqlxTJh0yleGHFFQ/pGCjJQLmDXMahJ67obtwW03D2YP78xYr08A81O5KilmlNZ9FlkEkN1z9mrrgzVzezG26+mBcXFON0I1HTQuPf6lyLl8mGKsChqCEl8cBE92q7yntQETHs0xqCLYL+9HnLX9uqIoDrPqW5SW9L4TPhtQtcljMZJb3xNRApBU45mQefDiEOqJ7NdYilSkPRPzoFG4D/d559+ltHxRgUKP/1wxK/lBZl8xlbiTRRYt3i2A8kiSRGiiyZjF96frQKiEiDm5jj4J2IFM2shh7E=

