#? Cert Manager 
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    api-token: AgBg2GRaYFMAG3kcWKp3mp216ZucOg3h7n8RIEwCUPdLWViQIECXNFY+5wyoL6JLvOyad+dSmF0n3WIIgRLhp8Xx0Ndn+ig7FkK1juMjJWUVroNcBs58RIVC0VuwRHR5BFvivRLACqVPHvE2vYaJe0QntKQ2qeAvf3X+AUw9kVjK27cqlHGyc7uWksNf7OeRMUoR/BTTcoju8LCEoD/m9XjpuTEtMFrhvZBh6i+HYAESdZC0HpMC9smx9wYLZQBONtTZ+bUCnuWNiWaKj5hT8kPu/RYj5DihZgKNZIa8LoduiJp9yBEvYn+zuJf884f9Ep/8KY5DvEqCj64eKjt+sfDw6qywKalgixvxVs/6o1uTE3cCd17YhHgdjpUooET7oOmvrAoY1mUZAaVG9RiBg72fVpAz8U5HrtmAFKGIiDpKDarbXIJgWtaBRL6cXN1row43XCblARKENB9XgalWJ/23UoEBJpo8AGXbUGNQHqVdk1wfWR3YuwEbI0hg4AINwiYlEWt/z+iXOTC9EXWwnSUClNFNr8gw3kGegxZFYoJo170PnYo9jp5txq44e7YEcoiTIG4rt1Z1xYtlcfmMDWshhNiQosic39qXDTx+Vfeb+x4oWv4a1M+3NIuxCGPZQy2ez4PSphusZ6pOvxJVlaYe8Wg+rAtPi08bXYO3pKZskpEUzarh8qm3EDoAQiIBmIYt5FlSjZ129NBSYZBthOuCcu9Hs8T3B22Rv++Y6Sm7bVypCom73cP7

---
#? Longhorn
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-secrets
  namespace: longhorn-system
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAEisCTokPTQcll2vvsQDZK67ZR8X2LN/ofYoU27KsIQAT6pCSflnNS6WqyVOqE6M36gr8thcpH1M12WYdCgWG3b9wPvV+XejlUGe5I0w40OhAyB3Twpf04yt3IpTG1vZbe7Dd1apQAwx6L8hOY2Xza0bVGSFFlgMK2lFNJq/QB1rcWE7AONNYEOfmJTC1Gr4lgP4qOkStq1E3ITiWQ8HUZJSt+vJs6EyOBDMGNGZOl8ALkWu2AQkjDwYUqACI5WlpU6OWGk9AJFPKWRHq4TIdQKPdy+9lDhpzebhjR2q8z4BEO7cM0X7K3pm9iKGB/rG8BVNXSmPnIFWdtiyXcRSCsHvb9hvqHMkS12krzGDe+ujYyomsMhxeY83k+affFcOpmbsnRJnTZ0uVYw3tJjP0R3mZjtGl2M3i/W95rV63NLEan+vNHJ6oPGBqZkl4RJmGufxvNgUQQLNp57Vy/SUmmotK+xUephiTT5bq9JnSNb3GzBD2tr1d94Rm+ssvqGaJCuLPDRQtu/Lmk1k60qdJn1OUBYoXWDVY26v2Cf7E/fY7nVXcgf5WFh8Z/Q4T071DfEZQ1U8s0hGQdrAPqjLaCiNti9v7uF92RASUAf0ksbUWEhM1nj+6/IXoYpQORR7Z1vvTY26Xbh5YdkOCGfodNZTvJKTqyywFUQNyvq/zCcMRxtjimm8Bs3HGGxT+TlHaDh5u2R29758eAPLmRe6pKCjQnYl0a6VQ8SJnisLp4oQ==
    AWS_SECRET_ACCESS_KEY: AgBhh/+l55v9WDxtFvk3aoQ3JtYNXqNVD8XerOwAyQ+YGnCiULNxGUV2bjDp289WE1XWqprEQpmzxTAFELjq9kIbHtBEmz03hHRWrvXjCL55l2DhaABWvc1xLj14rmiHuxPu7Cc1ZDruN5uoWmxVBt9pZBVymcVPp4qcWP+kUV8CW/QM0hMhypwbEck5rfsck++eDWgzjnJla3LRj9FVdyuctz0hUW1yYg+KJgT/33ZoIMkqmNSvh7nFG/Doa7tmBRPVhhXN5gq16RGpL/XS3Fx4ZlAypipwfYToDsbRvUudvvo/zrqCWYmPrQDGlHE/tWJ0fJH2kcFTN+8UeyCyXSih53z8THB7Ls4xLCQvj+KywHOcJa0E5KVhn0m1A1JdXzlGzeCpkq0O3pJoFXbLIbPJN3OSlgyFtQ8G9ZwF4wmEUZMFzRYE4fB6YRG2/fkih83lGjsLdS/WMc4XyxD0Fqsoi2/MklqYUB1uQ0whTMuiXDd3SFHPxyfvd2Ic4vxp196KIAIXtkYrxV3WcayebFkR/z1/5K+3HVhBRAZ9eBQfoXm+WyqqM8gvwpqRgRIqREjG0xLQhK5Zgi1Gremznqt+KsGHOq8EvnVvl+MZ8Fw3XzckeFs9hPhAA81/a8b9gFVx0k19ZzZOSVrIrXTaI4zt1bglPHAJ1nWp65860aiwIN/K3UFl2XhmKgnth4d4BFXd5eYyfN64TDNEG6i7glkt4y/Sse1Op3N34Sdq9FM0Yg==
    AWS_ENDPOINTS: AgAFlyvgswbCm9O5kQJkaFEjSVab33CG0SJcVG1AGyCO1YTv+pyS4I8zefYr44IrRX+h7Ikbt/XkII+28brtjkCW/YjGJRH1QdMlPqXCAZqJEf6+oGpuvHegbiwrRSkbwRZPlKiqHuGWejHx4mBjT+WQo69TeUHycHrbXfcWCcU4r2LYV1LjCv0MrY2Q51hoglt9I1s4vh5zQUZddCamGeO60wG/dZZw8c6EZBg/oC8efOrtEOEIOA/OswOS+DgLTs49CiUHqaZAKQchoUL3K1ES4O7LsApp6gp7jtwWZ6P3L8N0GY0VL174n9lncVkzHLHZqodHe8MjDLVqi2+x2ohWQrkaByU/FwX1dEAulD+ba2oQF5NzS6Gsm1rXLI1fhm5vLeGQo9sNs0h9vr23wJlmOrsmiDy/YVWtVHigiGPh8ql02ltUWKr/UxgjIcdU8D+85g63Mv92VTLbu/sLWyzCQp/TZCwmnN2Laao8uacsbiHypWXVBiCFAt+H4Htj0I+aPrLpIc6+sW/u9VJhEqT4qo8ocwtwuy0BBERJdDqEWgXTU885Vwx5TLSUjoNfVYBrhKT9vGPKgpLy/CDJToBZxpS9NTXIaCrNwx2VghPhTF9Oo654vjBjTCCFVXLMBkrIkOg80cWoKPT/Gt1kfleno0riJ3ul22q+m9C5wrFebL9fISP3LioExIdMqMh1Xdt9qnf7W96LMhvT3lcAslXYfaOB0adN2Q+0CZW5FQw=

---
#? Tailscale
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale
  namespace: tailscale
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    AUTH_KEY: AgA36QlStJtDeJkuMf+nHaXs0aQBAi7yWxp7emO/e5tk+NgW+WmxAUVbgPy2rsgFguWeXQKdHAY3LrwafwKyYOElpI+YT8EdPj4uNgm0PHoPnz94oNlSGVttrlvA6DqfKLxyoU73DfJZuUJdgNesvnu1uyhdwWDc5UXGatbV4AoINODYjZazW9JJjMaNhZSp6UrowV/XWViHQ0EXhSL4NcKT5BVUf7dGPXAcA4EOueoExWMB1xFbNYzCbdm14Ko1vNzLqCckz8ksoQpt+WlE8EREfGiBrSR0srC2ToL6Q/BV2gjU6xsgkXWhvMzKWcRRPoCGWTGpVTIhas04JewI0ughSxgbrCNEZhnRZXYJ30gBEoD7iszybLasl43GZ2WiRAsHsQBel5AACyXAIBMC5+tiD185IaZfYEIcEog5OGmpyPi9qGPtTlT02FheVd+YZ+uAIXVhHEWkgCJO9Fhlgl0E8EM4TvfZcqrf9xki0BEcNQ+HS7bG76uPOyj2MSSwmu2A8GOlKOWEPlubjXTYbv2AujUZT8p+1rKZQ1r3XoJshs6vwFTrS4fY94SqLBwlUKmQaCx+3jOL/xgNwfRLfBgeNCKbCaiOQq/YXJvbSQ5Gp9qcXf9lS1APvQD09E2o+A6YABTi8AV0GaeLJ6v4G7Upppl4wFFhYk992HbofzxJcL+RRKdokd8D6UN9FGiSN8aQhJQ32J6o0OKqw5JGvsnAOC8pwvj7dFzv+PGLsU3HzEjiuK8+N6ahjIc9RFm4uxYsTzNp8YvXCEk=

