#? Tailscale 
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-config
  namespace: tailscale
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    TS_AUTH_KEY: AgBGwZlUO7YDIXbks7iyA5KlU5xcIertqkqnSaEjtwBoepE12kONP5feKED3tnioSrmi9TveQY2ogoqFgwkZYQhAEXaXut5/4XcJVTBBhdUUFm4/pDJS6HPcyG18BcO/sCnV5gkuskmtRysL1pYZDiNDUpc0ieyuPmPU526Zm316/v99aZByHOgvmAjUvWVGrJzKMCLarDFYRXKtszgp81+NMb8xYwC3m/Ie5cKI/YMDAqNF0xgYqeRKRIfKog8ELxkEV2tHyc9d/AMpCJ7kkOv3yE+bPYooKlVY503mr24q2Sd+GcGyGH21ehkIXCOlojL6PoCAgfLar7752IX56EteEgkugi/0F++yCuULc72d3hHaKuzhfNocSirjl/svVyN0slf/dIS7qmG+B7aHxT2zFyh8dgc4MyjuVkIwVjBnHCPOg8r0JIV4KHxC3UkzPka00rQbI0WitcShpdjplYcwdewCScWx+bbsxcCfLt8OUZf0IoHELR79NenFYpM2xSOmiYNrf062lWvGhsy1aO8qSvU/Tnmkzo+TxrnVZ5LmdPEQ+I6rDc24/M6vwPHI+RS1sXi0PenON2oYUBzaJW4uDoZgqFVD8HnmCUJXPqiw3t6f3WiqeeOOtupYsEnYM+9UrG5kb5E98ZLW9FXwRSgI0bUZ4CYlkMloH9eUgbUQOdut91WgCW9lcGxK25ZfrfZeT5+0jL3CHBEsqoH5du4onXWwAVDpUMqTTm39vU0+jSoGyTB+OHxCQBbbg1z5wNnfQcriy5890Uo=

---
#? Cert Manager 
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    api-token: AgBQ+LJT0N5ltTgYG2bn7nOOTffT4joULhFH9tW5hM0kSVQOSJtmtCjw0SivAXmzYSJ6Qr5UPAONZrLQz1elGf+Fv9nsDcPOUsZVfPQkH7N4MpK1pTw3jVjWuhCR4+r0nl8HO4e2V3I3Zj1b3l5AxP+tXzPQf7LaR7sxGNaYJEHLV4Ca6C6h7MxX58t4l32XK2YNLaL5U4weEDs7XnKT4qC0L6PPg1gDDNA3DfsJVfiUC4dhxVD+49hwKqAPFRg4EAk/wY2ePINmbls9Spz2E8CBQm1Eqd6AjSW96hTfjzCSz+eP1r2V+ccqHfMafvaYoOTvNQx/1502EmVk+jJ8l3C5qP7TkjLnjIMkG/gX4CUeCU+UdML6YTAgfxYsPYsOT2lftw686CWnnpkaSS3b0yzukO1teHC4IS989SsG2ICUfww9uZH+l4XL6gJxdFOheHFpocc6zp3Ur/A/44CjMIVG9wkMkeq6a8A3WL9pPXGh2WQUx3hBm220SyPjEe1K+3gVLfHCqUTDKhjS8WtlDsjiazef7jQuQGcuATo6HjcB5NpuAOzpN5pR3O+bwukdaJYN1DLTT5rQ6vNSnLL26Hjq1H9TszEac4hgUQs5wZm5XEznZvHh/4nYncjuFqGBzwwTW5IPnUOTFlVE6T+SIK0Rp9DKtnN2B1UpESYDHQ6n/B6JPhZM11dyWoyAi7Ho8Ynwh6Q5m+uR018+nVjQR0VfMqwnA8pEfje0I1EcPqnal8RyHtTBeAJ7

---
#? Longhorn
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-secrets
  namespace: longhorn-system
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBa1JgjrmkAH8OpFtFwcYwP0+qctWTurxhI4psJwwgoYEal0VQuu3i+k28bilzHa8hUt1TMe9ZVghR0JYi0L+NqYYLNL1SoxemwOiAxsqKIOYnyYQ2VzripzjYuiaZWtkOszcWDdIYnF0QC2/wDp/bsx+7v2jPPcNrKaf0mhfuFYYkpPbYbfUTBNcKKV6yZu3pKJpYhgjTPKap+zeQBGCG6uD0lisa3XXeMpXdD200ig+KMeIr7dWoG6YQmxRPXkKh5uF7wdadQTQJfs4PkDuq1M69Jioum5C1chltLCiuD5iNHjKJHLMdnjPfX3/XwaNC9wcWWSQX4C21QTVOqcqkJSQO+ddvb0gkYIbGJ80LdvB7UOV/ZkCF3laT6qE1Lqhz6V+7WNakWgItrH1Jzi2kPmVC4aqoCFoCm7M29Ed1SFyHPJRoaplLoqoKPgpkZC4O+ecxCprfcKwdHMZDMpCshNxM14KAaM1sfnWKvp900UvWz4QMgNCNLT94LARN9jy8+RTi42uOvWcXdi939C+1f3bcboX/8tm9/uDWT8DaZ7sSfilveV6XMTlUVMvDmBp3S35voyYOP+1scFaeX9MbJsqdzmVtTrP50isn08yKmmtdV9ZwiiP6OJgso7tz2C8PNQb2juY892RnQyGBqgOYvbxGGOsJGfNLpAApcmK+8XFDE9yXEliVhFI4N1GnxXu49U2X1fag2VQ5mIwo7O+91NfzCK5Oz8KxvC/+BkU/5tA==
    AWS_SECRET_ACCESS_KEY: AgBTiAh71Zlxgv6pTPNF2B8dMtoXR7kBCTnTiv89IVfRS1t7UalRdX5VC52R5Hc3yKgUeCAf/RkLkdckCelJw2q5eJfNtwXVgimlgl1JNePejjZVzrAnCmjQU9mDlUrJOZXY9GDg58PD0Lz5r7QnZ0egZquRQuXI6KHhbFGQuR8BpExAk9eCSecu6LlwpGb3ghuZ2afxZz67LjIkw5HGEeAM89z292xAVL+H7sZp7b5LzuHrNINiZDoasqK7E9ikPorojzPxE4IXeeZdzBqXDy56HRkMLCriiEmFmkIThU2btGVfkdPMx18t0QiuS3IGREH1nibgEhGNLzJMmmTeloTAMCn+oeLnzP7tvbbO5cm4sCn7tYviC8YzWc9F8oBOl+CbtV8/4/q6rhZX6DkPmBohwe2Dkx2JL9JW6v3fzndQ7JtcJibndbYXdH0sHjUNyKuhT/Dxy/x4VZcK+TX3KfVLRmXClqxnynJ6lrINCvXQxgFkCKELSzBB0aH2ATGoaO2cjonKOb6TIBQH5+hU6OyDzjBRrIF7nNHUs7jjee/6SmO10PrdNHZd+kCJ1kM1WH49ORUH3It4iaKaZmT6BrhVo8Nwz1/9JLEyc2tszYiLBo+DSADkBlg4on1vcm0U7um6kasgBwRuxJEyNKn+G55ywVFYKzg7kSsjpxnIWILPUZyCxLMDcp/lyaCwQpWT/CSE0qYvJJfSqgOuTDELX34QcjBluQAz1PLnZN/74zpyzA==
    AWS_ENDPOINTS: AgBM6CDBzqBT8+Xd8K/4w6ASVOvj31Nzm48vbzPBoQ07qFnAQjpIuyQ6ng6nn0UPzm79JE2PRILv98Po40uriDe6Zlo282o+J9rYMLTRTAZOXvjejFh48nDFpy54wMPeDpciKkDA7r2MgV14/850HV2z0tZXDgnQ+90kbdJ1GOujp1RVw9rQh/9AbqiMAevseCEHnOrvA0jZ6UEtF6YD/SPIITt6q9yEeHg1Err8nG7o3Z8fTHpYo6Nbh+mNM4QoIGTulUysLsBsUlmtoViT/wAfLrlCs2+7iW1pvjlbE0AC9nMvLiyQOlPaeKmJJP03yTMPsJUZ5XeMM6TBrDgNb1HNS0/oZxLNGLYbb7w1qLoKiVv7a7dDVlsRsQ6eakNMjIOtFk9t4XG6h3eWGNWidhemY84l1CGQzZF/OnY6Nw6A4RxZvtNlk2Us1xa2RSrgDcPzjYq/+bzcNU42cz4dpIMDKFDDFBuTqwDc3Qf2vDmcvknYplEQIIa2LATn9Do9brtEOTeRQGO4swvfOb0sBA5wKfgfWfFoRhZj006yaMM5tNxJYk+Lzt35/mXzrMAFtS/0Fp4B8SjQtRRjOdlOV3f6Rv8FwZfTS6FLVvNV4BD/E2L1uRGTjmkEhc+LVKUBHRZsfJMeXk1FL9GJcj4lVSBxG7yKELlJFab8pWwoAxSOHhkjUvgVolZloyrf81aM8hLf8fptj3zoyJ0DYhqKZX57N6jwrkmg/Cp3ovYJi54=

---
#? Image Updater 
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-registry
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgBWwp3LPHEGuvE9DozOzk43dPu8KoUiWdRmMWkPs9AXGjtVdtpg7aUYWsDNI7/Ay81VQqsIGaqsF2xqt652DJi9Mk6dlLPuNlEcCp1CNoeXifd/XYVpvN+Aesf/tLN1J2Olf2t4UyG721n5v1bqWPw5RBE9HHrRH47NxL6t6EOvBstqjSjUAaILlSOgl72QvKdb5misnDHh2AAF9aYfl7iGcW5v2yPRthSgPK5EkHLs/eGYnnynFLrFqJEHxlislBcn30QpNgXFBoX7kLnqkCX1AXvzkFlyeCFWqpElJCauGfw22bYi9FVkME6oB9KTR9QB5Hia0eXT3RL5tucc4nR9mcAaPZJLic8uMF9gs0b3Z5hRMSZVgWH6nzLlo8EnSZoic328qhJXOGi04SXLvEyzZLZhh4TlLlN6lLlRJ+YWVIIM4LEd8sig+BayL/ey13bBIG60g5neRxdaIuQQfXLP3otV+4+sP6ZNzQxVhN6qDI0Vdn15g3Sytd8UVq6IeSkn3lXNaJt+A80jV2hjk8p+Tdg/ZQgyMxjQuQ5NdDgN9giGd2HNBv4gBWMRiVtRSANbVw3adm07HIKnjMzjpSzVjHm5CjTO9+w6zdUJ6A1uQquJK6ia4cOX6KNQWe7Ln+L4tzkaqhXaMg7O9ksAzpy+/PpUV9UlLqjHRJTcp3gScsyCg3+HZkP4Wyfv8e4Plp0Kmoo7xnSWMR82WbLzmG+uZ9Uv9e+HWEtGZGBp21n/syOwV4Xi2yAsni55rV05yU2yUeiwawCCcNoAtfQntPGaYJTR1BETp+Jcr7FsiGYy/NK9rVJo3BtBeiqObLfN6wapSpIk6kVGRQP/9jrssqRoLtpubplVq9qEziPobmGu1KC/jYaV17zdhVRUnpoCceX1WX/CvyF3mK4/CZ1YzMsBuLSLN/fPn4OUIfPlZDgVJvjeqMVl5sh257GczCMwuNO7bnPV1zHlIR9OQBZ7YaWoIVLO7OugKbKlkmaKqp3OG2cHarCFkeaKifbeyfQIbQ4=
  template:
    metadata:
      creationTimestamp: null
      name: github-registry
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
