#? Cert Manager 
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    api-token: AgB04piMn0vvfW00C2xXxRsLsbTW2ckfXfZ1pM+Kb2vxeTCseMGuKGmW9kPMaHTMW6mrKeuwIt4JF0Z2mStu/km4ZNyuARF3OyPHqM+7bLeykdztfW8ukL7Dbjvi5vFeQPCySSiSym1FoV7CTgjdrO6a8/M7rdCKQBzu+9fwiN1LhQeDYQvBBo8nPPqdtP6iYA8AfB7MWJBH0Nfc2nhM98F6vvGuoBy3LEA83US6vNrZhRqEuwFP39yIeAmgKg7DqUMb2wGRLKUuA6sWX3YwPjPMvXCB5kh/PNsJ9EYtpDIVWlifD3sAA37nxd7Oy6KNgM1mEoGsmSLCKpyDqq4+jJII3qo12Odt5YHkLJAP3nWccTIT2TcxB7/TAHwEhtDHi8W7ryI4Xx+9QKOJEELHmVFvKahy+iSUHTUPp5cimb83M4mvG0WXqW3cOXEozz7PS9vSyRogJe4eseUuUJD+ENbw613GmsETb0BEEfdvsAaq36fABCdd2g/nkOv57j+dLTwPCDO5PWw+LYxQplQd5VPIRXTnSzXlJfjFVquyuATzQvSHjcMdU8TExK/6GrjWpdrZYIQ2iMHpXjGI0uIXMPuYpTlZw5ALfwBmfMHKx6k5VNjTEz0ZY/4543c68fRe3HDECwyFGelEfXloYfZk+4oK6/e5VqffgQAEU7hGp/JPsqlRwkuL5WxsbqYP6jZLB8QitEHqXPu4+QL+0VAaLKJFc08Gr4UVU2iT1IoBj0go4npxEHKkgELp

---
#? Longhorn
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-secrets
  namespace: longhorn-system
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCBQSd2DBQEVBjIdmTXfT8E1W1WvGwUiar24qMhqpgKDIGMoj/Na1ed4ZPM1+I/Z8/oIM7q7XGzkchOd4D7ogPL0YFy6EY9vhH2Gj8ycJjU4hCvfbIbdRjhuMKjSQpNUAQUqpOs6iFt6kCGtg8jOT9Ka8P+gH0CxiHQKMg8pVOR24WLa/k1Rndol+wXYK7WrF/2FdIpKq+RkxH0o4m5FjYOBfRrg4tPly/CU00wP2zsUFfU4Q9l0YltcCXwsZ5yfR8IrLHYdTCV+2lsBMFDRt2Ho0tA18R0tFkqFe7jHlfCLpBglzpxMKO7IuCYkwae4UXT7nIQOpSzz+bF/TjJ48p6yxvS8a/RV6B/EDjegdP3hlq5XDQ43UGTqh/5yMo/xNnI9OsE+IOBUFkw5NGXMVM7LrqiErwp4xgAPCdCysCq14PeqtSKdvTu7vymVFHBs3Xcxrl8dHcIWVyiu5tG/XQs5WddXRKKAIrw3zZTqzCN58+2IKBhTvHgRuBe+Y/fUuF9QmkFYOwn0ctK/FStN8Fa6Hqa4Vn/uVfAo3mzJNj3UsL+Z9VLmJbuxGiiGB7RUkBK8v5mEJb+SdMX05dXYqzFA0DWpgjPR1oNH62R88VNs1qZuI0hL2REvRtK7b+z6vUSjF9I1OcHXDGLAsb369AY7/28NNCE8eBbc5XnWruDYezXx4LKrk1cv2+GH/OX7+iTt0hehRm5SQhxBt23d68fG90RBpRpc5mV7T+N1QIXrw==
    AWS_SECRET_ACCESS_KEY: AgC0TWmcw/Ijah6N0xUerZ59aVrB2XUil/E/WJTQrb1il3xcIwgL8M0nVUxyCnm8VDPhAY8H6BawZxzKFegiqdaSgzroxPEytXZUMp8H7awQ4W4pq8EVCtJv0zdj7gu+e8MP6dJcMEnXE2ZLnvj7BbqoWOvp1ly3/GUPNbjHA0HJPeXixtteO7w8Ta4FkowZlKN0/GRLGrXv575jgEp7PLHU+lEArOs44yAM48yk4FMuI/as93F/EyuTVpYT9rIXD3M+WbVIHenRlXOfC57vHbE8DUhf3dnnGWlTLl8CcZ07DVFCXanEK+v3G3Ihh9t6BERNyn92wm7G3/FJ1/E51dvmyAjRMGiGBzIumuaaQiwubR50MwGbn3GCYqx03zbLEM2QCE2RVdZ1beq2QwXK9rw4ZCWTfSfyurSzffWbGASdGFiOAzC0/WFwmoW0DBa7n0fvhPXOKMnIlDJQYQrIm1Dx5u8v+C9RG8GZro1dhpEf0ox/J7Xx6lbZ/YRLGMFhgjmWLAawQO//zSRbAEeXr03TqSrxA/zqti7i5RZe4FyA//wTicAXLWw9fmTSS6BSR64PdRjebPQdTQ6SVLVy9y2g8Vlui8ndPfdxl3KKHb6eT6J/JQEc3LazOrlNev3+8vjC3RGTRC/+13qMoQg4q8Sg9irrautb3UvSe0WNS7KNSHkeWTuLR24+cvj3hG/GBPxxLLYhjX+zl8JJ7bEzz0FS96fMQgKeAyJagt4+ZfGvhg==
    AWS_ENDPOINTS: AgCgs9kikTdDDoxinrtCzJXyu+E/iHzU8nrheNxZs282N3SgdI/7QMftlRvpLAcRLiChHHwBnuzOV2SuSZM3lTnI4s4sija4D5qEmxUskWgAivtI9u9VAPvQAA3Z7HM1vu153UFPFa7v/fP12NZgSJcIyBxv5IDXjp8EhpJ8/kZlsQaKAjFUereJKTiyFv2MWZYGQjM1OmCLu1xHfQJKFB7p0LgUYX5/JBjYZFqlWTzAksgRyVYzEjCS3sUdBgppgnXlZgxxWmj0EjnLcoGH3xCS8RfuTWHC9gt7ZgW2a4d04PnKq/HMUwrdOkHXT/uXNvIJWYRJVBq8uYpwzI8AqeAxk4KZZefcujJcD66qq+hwdQuUwOF1ehEfZU2L0ODCwHvuY+k6ivB0u70rBRlux2yYoMqo2YLOJtiLL2syKX27tYeltRYsq8mgR8Si1Cez+lUs+ynYMxGvLzfBU7sUezwfBLGLl5pe4hE/DOuI6/fElUAj+gAslgBQssZ7KXW7ZBPM4lgR36WmAHaNLoZ4W1vdmsHSlO5PT51+4NluV8fQmGLj1dM4bdlU5UyKB8PwCMHPgXBLCkF9LWm1TkXHTa0j4tUaAwzjFsarQGeB9x0rNptU45aCpotOULe4jH2S+cDc/NJWLJycbEKzko+czUZexlACTereVGQ2MxPFvWNj4Vz5E1Hbit4PCLo6tVm+MEfQ7xyxYt8vv3KgEJn1KSM4FM06IFFvqlnQOv1cavc=

---
#? Tailscale
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale
  namespace: tailscale
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    AUTH_KEY: AgBIBHjUIVOanw4gqqVz53j2bvRrmEtqgnyEoQZlcrrVDtBC3//14eIulu1fTYD2gCw2RcLeKgdAqTmXtdDI43ijEqKvRiqEjR6GV0EQxnwHgbGEpc8l4CXAgEWXuJB7a75oruGc7WMQY32Wv5ww+0oj6/hgWqaYmClcRvK3QH+kZLTpq3d0+0Vrn+hFa4X94+9vKuWZg9X2gtt7RnHlUOpEW6xbWs9Cn+MasymJG0iZoxLICxsKFXDkfEs/vIolD+fJrjOMlxGCAbA1eVCfDZNGzMEwudMR/z45dqFe1t4oucK38M78ABg+XgtEy7187hcrc+YCxbrwQFbd0UTzCmrPiiVGZvnrz+RDXricH5pJkw0mUlK/hFNxJ+XxRYLy5PnPgfFKqjvmsHY3N0WxuJ7xoqKz4lik8LdI5cnfH7SzzEmvWbfMHhe8E2qVTDfESNbYe1mlYPf3cRuuXuL2BiP6lngLeNA3/Gw26Wb+lvdkljKI4Nk51hu9dkJBTxhLs1tEIQsDdgInVbDJZzAx5Qu04R0upnrzCH6OK07VfbT15YNkZzXyUZ2gqVfYdVZoDoz8jnM5phR+1ZBWTzWFSMOKMx29dfF7aXuw4IzWq0mi31Rz+sKC6USb5zUM80OTlLWXMiVNXMbbjssWXCoG7LYWbSVxdd46a45gQWoDBUUuoeQJn0xPshh10Q7oHYu5Kn7YacG8t0E+JQ0YWuh+tR2draNXQYGLa9MA+l9OjNN76a6cfQf9avWG1Cf7xUKFTrAHvqyJkqosDAo=

