apiVersion: v1
kind: Namespace
metadata:
  name: tailscale

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
spec:
  project: infrastructure
  source:
    chart: tailscale-subnet-router
    repoURL: https://gtaylor.github.io/helm-charts
    targetRevision: 1.2.1
    helm:
      values: |-
        tailscale:
          auth: { secretName: tailscale, secretKey: AUTH_KEY }
          state: { secretName: tailscale-config }
          routes: ["10.43.0.0/16"]
          extraEnv: [{ name: TS_EXTRA_ARGS, value: "--hostname=k3s-dev --advertise-exit-node" }]
        image:
          tag: "unstable-v1.63"
  destination:
    namespace: tailscale
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions: [CreateNamespace=true]
    automated: { prune: true, selfHeal: true }
