apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test-workflow
  namespace: argo-workflows
spec:
  entrypoint: git-clone
  templates:
    - name: git-clone
      inputs:
        artifacts:
          - name: argo-source
            path: /src
            git:
              repo: https://github.com/MP281X/dicantieri.git
              usernameSecret:
                name: github-secret
                key: username
              passwordSecret:
                name: github-secret
                token: token
              branch: main
      container:
        image: golang:1.10
        command: [sh, -c]
        args: ["git status && ls && cat VERSION"]
        workingDir: /src
        # image: r.j3ss.co/img:latest
        # command: [sh, -c]
        # args: ["img build -t dicantieri:latest"]
        # workingDir: /src
