apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: default
  # annotations: { argocd.argoproj.io/hook: PreSync }
spec:
  template:
    spec:
      containers:
        - name: whalesay
          image: docker/whalesay:latest
          command: ["cowsay"]
          args: ["hello world"]
      restartPolicy: Never
  backoffLimit: 4
