apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "1" }
spec:
  project: infrastructure
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 10.24.3
    helm:
      values: |-
        globalArguments:
          - "--global.sendanonymoususage=false"
          - "--global.checknewversion=false"
        additionalArguments:
          - "--serversTransport.insecureSkipVerify=true"
          - "--entryPoints.postgresql.address=:5432/tcp"
          - "--log.level=INFO"

        ports:
          web: { redirectTo: websecure }
          websecure: { tls: { enabled: true } }
          websecure: { tls: { enabled: true } }
          postgresql:
            expose: true
            port: 5432
            exposedPort: 5432
            protocol: TCP
          tp-kubernetes:
            port: 3026
            expose: true
            exposedPort: 3026
            protocol: TCP
          tp-database:
            port: 3036
            expose: true
            exposedPort: 3036
            protocol: TCP
          tp-ssh-tunnel:
            port: 3024
            expose: true
            exposedPort: 3024
            protocol: TCP
          tp-ssh-proxy:    
            port: 3023
            expose: true
            exposedPort: 3023
            protocol: TCP

        ingressRoute: { dashboard: { enabled: false } }
        rbac: { enabled: true }

        providers:
          kubernetesCRD:
            enabled: true
            ingressClass: traefik
          kubernetesIngress:
            enabled: true
            publishedService: { enabled: true }

        service:
          ipFamilyPolicy: "PreferDualStack"

  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions: [CreateNamespace=true]
    automated: { prune: true, selfHeal: true }
