apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "1" }
spec:
  project: infrastructure
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 20.1.1
    helm:
      values: |-
        globalArguments:
          - "--global.sendanonymoususage=false"
          - "--global.checknewversion=false"
          - "--metrics=false"
          - "--metrics.prometheus=false"
        additionalArguments:
          - "--serversTransport.insecureSkipVerify=true"
          - "--entryPoints.postgresql.address=:5432/tcp"
          - "--log.level=INFO"
          - "--experimental.plugins.traefik-real-ip.modulename=github.com/soulbalz/traefik-real-ip"
          - "--experimental.plugins.traefik-real-ip.version=v1.0.3"
          
        ports:
          web: { redirectTo: websecure }
          websecure: { tls: { enabled: true } }
          postgresql:
            expose: true
            port: 5432
            exposedPort: 5432
            protocol: TCP

        ingressRoute: { dashboard: { enabled: false } }
        rbac: { enabled: true }

        providers:
          kubernetesCRD:
            enabled: true
            ingressClass: traefik
            allowCrossNamespace: true
          kubernetesIngress:
            enabled: true
            publishedService: { enabled: true }

        service:
          ipFamilyPolicy: "PreferDualStack"
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions: [CreateNamespace=true]
    automated: { prune: true, selfHeal: true }
