apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "1" }
spec:
  project: infrastructure
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 20.1.1
    helm:
      values: |-
        globalArguments:
          - "--global.sendanonymoususage=false"
          - "--global.checknewversion=false"
        additionalArguments:
          - "--serversTransport.insecureSkipVerify=true"
          - "--entryPoints.postgresql.address=:5432/tcp"
          - "--log.level=INFO"
        ports:
          web: { redirectTo: websecure }
          websecure: { tls: { enabled: true } }
          postgresql:
            expose: true
            port: 5432
            exposedPort: 5432
            protocol: TCP
        ingressRoute: { dashboard: { enabled: false } }
        rbac: { enabled: true }
        metrics: {}

        providers:
          kubernetesCRD:
            enabled: true
            ingressClass: traefik
            allowCrossNamespace: true
          kubernetesIngress:
            enabled: true
            publishedService: { enabled: true }
        service:
          enabled: false

  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions: [CreateNamespace=true]
    automated:
      { prune: true, selfHeal: true }

      # globalArguments:
      #   - "--global.sendanonymoususage=false"
      #   - "--global.checknewversion=false"
      # additionalArguments:
      #   - "--serversTransport.insecureSkipVerify=true"
      #   - "--entryPoints.postgresql.address=:5432/tcp"
      #   - "--entryPoints.web.address=:80/tcp"
      #   - "--entryPoints.websecure.address=:443/tcp"
      #   - "--log.level=INFO"

      # securityContext:
      #   capabilities: { add: [NET_BIND_SERVICE] }
      #   runAsNonRoot: false
      #   runAsUser: 0

      # ports:
      #   web:
      #     redirectTo: websecure
      #     expose: true
      #     port: 80
      #     # hostPort: 80
      #     # hostIP: 192.168.0.1
      #     exposedPort: 80
      #     protocol: TCP
      #   websecure:
      #     tls: { enabled: true }
      #     expose: true
      #     port: 443
      #     # hostPort: 443
      #     # hostIP: 192.168.0.1
      #     exposedPort: 443
      #     protocol: TCP
      #   postgresql:
      #     expose: true
      #     port: 5432
      #     # hostPort: 5432
      #     # hostIP: 192.168.0.1
      #     exposedPort: 5432
      #     protocol: TCP

      # ingressRoute: { dashboard: { enabled: false } }
      # hostNetwork: true
      # metrics: {}
      # rbac: { enabled: true }

      # providers:
      #   kubernetesCRD:
      #     enabled: true
      #     ingressClass: traefik
      #     allowCrossNamespace: true
      #   kubernetesIngress:
      #     enabled: true
      #     publishedService: { enabled: true }

      # service:
      #   enabled: false
