apiVersion: v1
kind: Namespace
metadata:
  name: traefik

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: infrastructure
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 28.1.0
    helm:
      values: |-
        globalArguments:
          - "--global.checknewversion=false"
          - "--global.sendanonymoususage=false"
        additionalArguments:
          - "--log.level=INFO"
          - "--serversTransport.insecureSkipVerify=true"

        ports:
          web:
            port: 80
            expose: true
            protocol: TCP
            exposePort: 80
            redirectTo: websecure
          websecure:
            port: 443
            expose: true
            protocol: TCP
            exposePort: 443
            tls: { enable: true }

        rbac: { enabled: true }
        ingressRoute: { dashboard: { enabled: false } }
        service:
          type: ClusterIP
          externalIPs: [10.43.0.100]
          spec:
            externalTrafficPolicy: ''
            clusterIP: 10.43.0.100

        providers:
          kubernetesCRD:
            enabled: true
            ingressClass: traefik
            allowCrossNamespace: true

  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: { prune: true, selfHeal: true }

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-external
  namespace: argocd
spec:
  project: infrastructure
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 28.1.0
    helm:
      values: |-
        globalArguments:
          - "--global.checknewversion=false"
          - "--global.sendanonymoususage=false"
        additionalArguments:
          - "--log.level=INFO"
          - "--serversTransport.insecureSkipVerify=true"

        ports:
          web:
            port: 80
            expose: true
            protocol: TCP
            exposePort: 80
            redirectTo: websecure
          websecure:
            port: 443
            expose: true
            protocol: TCP
            exposePort: 443
            tls: { enable: true }

        rbac: { enabled: true }
        ingressRoute: { dashboard: { enabled: false } }
        service: {ipFamilyPolicy: "PreferDualStack"}

        providers:
          kubernetesCRD:
            enabled: true
            ingressClass: traefik-external
            allowCrossNamespace: true

  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: { prune: true, selfHeal: true }

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`traefik.mp281x.xyz`)
      kind: Rule
      services: [{ name: api@internal, kind: TraefikService }]
