apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: infrastructure
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.23.0
    helm:
      values: |-
        server: { dev: { enabled: true } }
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions: [CreateNamespace=true]
    automated: { prune: true, selfHeal: true }
