kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata: { name: infrastructure, namespace: argocd }
spec:
  description: infrastructure related apps
  sourceRepos: ["*"]
  destinations: [{ namespace: "*", server: "*" }]
  clusterResourceWhitelist: [{ group: "*", kind: "*" }]

---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata: { name: infrastructure, namespace: argocd }
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/MP281X/argocd
    targetRevision: HEAD
    path: infrastructure
  destination: { server: https://kubernetes.default.svc, namespace: argocd }
  syncPolicy:
    syncOptions: [CreateNamespace=true]
    automated: { selfHeal: true, prune: true }
