apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  description: infrastructure related apps
  sourceRepos: ["*"]
  destinations: [{ namespace: "*", server: "*" }]
  clusterResourceWhitelist: [{ group: "*", kind: "*" }]

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  project: infrastructure
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: infrastructure
    repoURL: https://github.com/MP281X/argocd
    targetRevision: HEAD
