apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  description: monitoring related apps
  sourceRepos: ["*"]
  destinations: [{ namespace: "*", server: "*" }]
  clusterResourceWhitelist: [{ group: "*", kind: "*" }]

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - { cluster: dev, url: https://kubernetes.default.svc }
  template:
    metadata:
      name: "{{cluster}}-monitoring"
    spec:
      project: monitoring
      source:
        repoURL: https://github.com/MP281X/argocd
        targetRevision: HEAD
        path: monitoring
      destination:
        server: "{{url}}"
        namespace: monitoring
      syncPolicy:
        syncOptions: [CreateNamespace=true]
        automated: { prune: true, selfHeal: true }
