apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: app-backup
  namespace: longhorn-system
spec:
  cron: "0 0 * * ?"
  task: "backup"
  groups: [default]
  retain: 5
  concurrency: 2
