apiVersion: v1
kind: Namespace
metadata: { name: homarr }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr
  namespace: homarr
  labels: { app: homarr }
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/match-tag: "true"
spec:
  replicas: 1
  selector: { matchLabels: { app: homarr } }
  template:
    metadata: { labels: { app: homarr } }
    spec:
      containers:
        - name: homarr
          image: ghcr.io/ajnart/homarr:latest
          ports: [containerPort: 7575]
          volumeMounts: [{ name: config, mountPath: /app/data/configs }]
      volumes: [{ name: config, configMap: { name: homarr } }]

---
apiVersion: v1
kind: Service
metadata:
  name: homarr
  namespace: homarr
spec:
  selector: { app: homarr }
  ports: [{ port: 7575, name: homarr, targetPort: 7575 }]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homarr
  namespace: homarr
data:
  default.json: |
    {
      "name": "default",
      "services": [
        {
          "id": "9aa259f3-eac1-4081-9cda-6db6ec6ab12a",
          "type": "Other",
          "name": "Traefik",
          "icon": "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/traefik.png",
          "url": "https://traefik.mp281x.xyz"
        },
        {
          "id": "fe16ccb9-7b9b-4ea1-8497-3ff30b859a2e",
          "type": "Other",
          "name": "ArgoCD",
          "icon": "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/argocd.png",
          "url": "https://argocd.mp281x.xyz"
        },
        {
          "id": "2153c5d0-7e02-429c-9a71-26055bf32e95",
          "type": "Other",
          "name": "Vaultwarden",
          "icon": "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/bitwarden.png",
          "url": "https://vaultwarden.mp281x.xyz"
        },
        {
          "id": "0f42265a-861d-4236-9a82-a3966459af13",
          "type": "Other",
          "name": "Keel",
          "icon": "https://keel.sh/img/logo_small.png",
          "url": "https://keel.mp281x.xyz"
        }
      ],
      "settings": {
        "searchUrl": "https://google.com/search?q=",
        "widgetPosition": "right",
        "appCardWidth": 1.2,
        "title": "Dev Server",
        "logo": "https://avatars.githubusercontent.com/u/42154987?v=4"
      },
      "modules": {
        "Search Bar": {
          "enabled": true
        },
        "calendar": {
          "enabled": true
        },
        "ping": {
          "enabled": true
        },
        "dashdot": {
          "enabled": false
        },
        "date": {
          "enabled": true
        },
        "dlspeed": {
          "enabled": false
        },
        "usenet": {
          "enabled": false
        },
        "weather": {
          "enabled": false,
          "options": {
            "location": {
              "value": "Udine"
            }
          }
        }
      }
    }
