apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: default
  labels: { app: minecraft }
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector: { matchLabels: { app: minecraft } }
  template:
    metadata: { labels: { app: minecraft } }
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:latest
          ports: [containerPort: 25565]

---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: default
spec:
  selector: { app: minecraft }
  ports: [{ port: 25565, name: minecraft, targetPort: 25565 }]

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: minecraft
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik-external
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  entryPoints: [websecure]
  routes:
    - match: HostSNI(`*`)
      services: [{ name: minecraft, port: 25565 }]
