apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoprism
  namespace: app
  labels: { app: photoprism }
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/match-tag: "true"
spec:
  replicas: 1
  selector: { matchLabels: { app: photoprism } }
  template:
    metadata: { labels: { app: photoprism } }
    spec:
      containers:
        - name: photoprism
          image: photoprism/photoprism:latest
          env:
            - { name: PHOTOPRISM_ADMIN_PASSWORD, value: password }
            - { name: PHOTOPRISM_HTTP_HOST, value: "0.0.0.0" }
            - { name: PHOTOPRISM_HTTP_PORT, value: "2342" }

          ports: [containerPort: 2342]
      #     volumeMounts: [{ name: data, mountPath: /data }]
      # volumes:
      #   - name: data
      #     persistentVolumeClaim: { claimName: photoprism }

---
apiVersion: v1
kind: Service
metadata:
  name: photoprism
  namespace: app
spec:
  selector: { app: photoprism }
  ports: [{ port: 2342, name: photoprism, targetPort: 2342 }]
