kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata: { name: app }
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fromBackup: ""
