apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test
  namespace: default
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    scret1: AgAGYL3b08cW5sNkK86rOYDOZ+OCZzCkehF08TWpRpW12ACXJJ9K5psADyXbSQ6xZKuDBTAtIuI7YGW6ssQt85qNSPgYDfimtf71RvThPHffPuPQln2l3f4ddNQ3Pa5gAyFZSQShSccnk2OM0emz74hlaA5nc4DxiYCbRYdIZPUIynTCt86GeCSxLh8EWMkh5V++9U6XFvBxc+lkq0PA+JR/rfaLZdgIT69hsTBKn+TZXY6FR1UNIc9A56mZ8W3bKt0T3VUGSmQzaK8HoRQ50yvxlPS4HszH6TB386DdzT1eTVQpbRrUa5HfDNNTIRR/zw7QahEBH1yxjzctK8dMgx0MGCT1mCPdJIUvBC7wPDr0Tbdy1zhHbRLeRe09zjC52m1VOn1txLEZZTmerW3KnHyP/YCxAr6Jlss/sFWt+t4MGvESRnYPHtnowECiGWSFYX208xPbMtyhhpijAbxUyKXLuzl//miWPjc1/mTmjXtDfOmiBtkVIhsULvyeNYzVTTE8wJofl9sRwxrk/yEM3aJ2mev84G2qzVV6SO7XI88gibVM1JKVnGSFBjxdu2LYf6a1p18c9KJJjApSsQ36x3YeVV68h7EKbFswTz7OJ6F24Cf0rd3QDzGFgNOn72KZQaPHBmWU9HuQvZxBoxb6FZrAtCHuMfdafQSBb9BReVHz68G+7omlQvv/+ZwbfmpKXo+eAvTpBxE=
  template:
    metadata:
      creationTimestamp: null
      name: test
      namespace: default
