apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test
  namespace: default
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    scret1: AgBJxDO6mLSYlJ2GAhTxPn3mdEa/HOkbo4kc/lb4FCkrhx53dT6Smz08Hsndq5n/T5x0z6nGTTGPavhTBkRh2W5axVXrYyNBaKNKIyCu7+oSJeFHlBARmjFVAK2SwNLEsZPegqSi5lIYIqgt9o4FQQ2q3c8dhJImVKs44Kz1LcpJEwZJ+9GHEmZj5N/WxMeq9og7mLBsJw8jcz/pnonnCXTlYHFe3NEBwCtNjnrml3LBie8hmKea9Ll5Ow/aRtJuYB97YiWxtYElAnKfkpoqe1kjKSkWNJ14K/Oc5040RndD1kS6SsJN5PIkWPyILlvjTcVqK4NGEY1EQBAvTvZ5E3SnDBpxbYNrTKq2XEk3aOgjMpXzENw5d6LSiDZske1uzd/K1ZUnvHjrhxl6BcDD5pzMDxFsZf+0T+jTm3OeGAE1xcDsLq9yRc9Ty75XQKqXniSgV20bv/GauE8Y2ygbOtGGPw5oLq27ynpq7nNaur+wFPRh53tkhq0rzTePVvmos6YxdSjCmMPKLuGTsWt73q1o1kbrXG24QGft4KxdUcGQWzjBzvkEOafqWxq1Nt/bdpF/SLdzhuNGhz7k50YOkN9dvznziSspADF++OD9tjgWhlNN6oZ9v+vYf6MPOtDCuzCpWUN8DznmRsjeZSFxP4ZzJc8BDimhnvoX+dB72WU0nHURU/BakszZ9Ycb5kwdR/+t0DXt4o4=
  template:
    metadata:
      creationTimestamp: null
      name: test
      namespace: default
