apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test
  namespace: default
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    scret1: AgCJmLgnYbZvSPgvGihRnOs4GFjR0aFzQMVXxZ/tWprfnMnDE0DmqHc41USSRyyLJK2GoG9wG0pnegoY7HgqszR+bB4cELCn723NryShrUR7QUw0Sq4/bprW9YCeWmCt1WL9JkuS65qiOd0u/yEHrc8+XO6xzlzcWnI2cpoff/tE8B+u6RaVu5SN5r+A1TwJ8RRMFdmeM0y5uGnjqvtF3kAcE7dX0Lzrxq9lqidzbpvQEhDr/DUE2wZqvNiowPh9xm9+aSnUcqSw4Su7VGavtT1NSyTRX2RWiK0IUC18r75HIV/hgYC7U/JmHG6T6IiKRooLjTo6P9eNre2kjjYG24iBYv2AokOQLZKIxMVGcbi1mryxp1oDryANQzGcHd3A+rPhYAZQh9PW7mHgskK2aVZ9f6yMNiQakEfcn+W1NLRQd6paW1o6fVu0kr6tm3G7Gs1hOVrAV++Dufu+5TTtiWZmud6cMhO6pop1bRbaqmlykVxaADcCqP/8brIFbZ4yL14rNCCTXLdew1ZTCPqisSnDoDewmd7pCHwkXnQfLZ10ygnu128NiOGIvrDPO/Cbxs9Apj0atOyKto82CumusIDqJGZgxuQ/k9D5+5jSoML4GKTlPAhPTsYdUoVXdgKNVzI3MAYQThtr3QqfGMkWOEbpvJrqxyfxswEqXRq9zK/qf+XXXRdFiT6ra0gUbWoCz0V9sKCTTuBaW9V45ZFD4mM=
  template:
    metadata:
      creationTimestamp: null
      name: test
      namespace: default
