apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test
  namespace: default
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    scret1: AgAb6SgKnhwUFY5cZmeA0ABgQmzVMXTlnBmHZ5KD5hZ4mzou7Bu9VKVGQjWykGGrMWUWHBP1fY64dxuM9/oeEjiqap9XspUiXeGHdOT51hVgNE2Hl694VETEC3GVdY6eiqdklUN4KZmvm6rv4TS+KfCM3VtkVvsIiT5eE13iw+6S7Reg3UzE4qJHKhODJoIcn0Yftk5aGrOahz+AzUyXuAMYRtCvh+xWs1mq6MiWaIvR2pgJTcEZ6kJygJE6XSI60PygUxfv9RVvM4H39ql6iTqHETJMeZ2W83hKWHUFUGfJVTZsFeGYFl76GMpWcHU0Mwi18XLtVm0ZYiJZvmz+H4q19pMU8dsH/6GXaVEGPbvRQVj6pyL3p9HBxYYGII2me6KboMApph2vf9AjECnTCCctYMxmqvn6eQ+kOAmzpVnjZJ0sIJwPS2nuY71LBBxQO1NDtBKUXmadROzYk3m6+4/s03OpVAE/3roxUkpcocJ7M2vPEASEyfImexMnCyNQd3+io3cU7SbxrZTllG93TtG6n5Yb8m+5CRD8FBYjV53vQ+7E1jyMpkYDeeX72USzykLIEGbwum4M/UsadpUvSjx7hVFEnMDfpJpXW9qEENugyjdbfVMDqo8/L3I1eKdi0QRMXzxo+vOIWra3cQZOxn4hwyW7Ajj0oRgRnuOrvE2eQrETIW69M++so69R+Jt4h/a47KY1p9M9s+R/z6xVYdc7
  template:
    metadata:
      creationTimestamp: null
      name: test
      namespace: default
