apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test
  namespace: default
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    scret1: AgAZr6vffHF0I3xOzPvLYNh8Pt9EIuALROfnacy8p4PD5BJNBKstJyIPYi+AQaWo5//jgm6RakLzoUUO7iDgRcNBslfrvbcNwUMGPE0DvSru2ciN15F9HTlzry0wk9wSrJrbG4Sn6fHp0+pLco8D2Y4n2A60Y4mjiVwg8Al9lJ+kNg7ojCqwJ3WHCu13+mBY90epT43mpIx4bvCwKePwzmDh8CcOW/9ItX4897ldadlhb9+nSKeXIO4V727RTDFvEJ7AkkA0GXEQmMwNn92spBEypUnO2fPAjZfKKKqQftwATTnECFY9zk5AqcftFoFQsS+brUSJtILY7OX/IIKaHCphAAg3sYx6F8us6/pvaZuupuflaBRb2rhv0J6Brg0ct2W4Z+8/DtnsA+ryXfFFDabzuRQtsG+eGg/WR+Q+ov6gj84toKCCdTVrSHzRm3fYxiXGlLZ0UoN88X+QywWc7VKCxXhrk4WNSSwl0WPJgBIze4vwxUqIQwK2eyNwXmVROrvUl6MWQDwx0piNeZdPH2sd/+5vDULYpiVlMiNXeUF8SxxnUuT4RoSW4/caQnxxKMM2zvbhk38miAs/UPKWp4bJ6p9Hb03//4t8019vJ0Um5mHT97zjem2PbNum6i+jGeXakf8xbTqon+OJLqSiGfCJnfP8tGlYKWnagS16NP97+Mnl1Tk04t3h5cek/1J95d9mxX1BSVHU
  template:
    metadata:
      creationTimestamp: null
      name: test
      namespace: default
