apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: test-pvc
  resources:
    requests:
      storage: 2Gi
