apiVersion: apps/v1
kind: Deployment
metadata:
  name: trilium
  namespace: default
  labels: { app: trilium }
spec:
  replicas: 1
  selector: { matchLabels: { app: trilium } }
  template:
    metadata: { labels: { app: trilium } }
    spec:
      containers:
        - name: trilium
          image: zadam/trilium:latest
          ports: [containerPort: 8080]
          env: [{ name: TRILIUM_PORT, value: "8080" }]
          volumeMounts: [{ name: data, mountPath: /home/node/trilium-data }]
      volumes:
        - name: data
          persistentVolumeClaim: { claimName: trilium }

---
apiVersion: v1
kind: Service
metadata:
  name: trilium
  namespace: default
spec:
  selector: { app: trilium }
  ports: [{ port: 8080, name: trilium, targetPort: 8080 }]

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: trilium
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`trilium.mp281x.xyz`)
      kind: Rule
      services: [{ name: trilium, port: 8080 }]
