apiVersion: v1
kind: Namespace
metadata: { name: vaultwarden }

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vaultwarden
  namespace: vaultwarden
  labels: { app: vaultwarden }
  annotations:
    argocd-image-updater.argoproj.io/image-list: vaultwarden/server:latest
    argocd-image-updater.argoproj.io/auth-server.update-strategy: digest
spec:
  replicas: 1
  selector: { matchLabels: { app: vaultwarden } }
  serviceName: vaultwarden
  template:
    metadata: { labels: { app: vaultwarden } }
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:latest
          ports: [containerPort: 80]
          volumeMounts: [{ name: vaultwarden-local, mountPath: /data }]
      volumes:
        - name: vaultwarden-local
          hostPath:
            path: /home/mp281x/storage/vaultwarden
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  selector: { app: vaultwarden }
  ports: [{ port: 80, name: vaultwarden, targetPort: 80 }]
