apiVersion: v1
kind: Namespace
metadata: { name: vaultwarden }

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vaultwarden
  namespace: vaultwarden
  labels: { app: vaultwarden }
spec:
  replicas: 1
  selector: { matchLabels: { app: vaultwarden } }
  serviceName: vaultwarden
  template:
    metadata: { labels: { app: vaultwarden } }
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:latest
          ports: [containerPort: 80]
          volumeMounts: [{ name: vaultwarden, mountPath: /data }]
  volumeClaimTemplates:
    - metadata:
        name: vaultwarden
        namespace: vaultwarden
      spec:
        dataSource:
          name: vaultwarden-restore
          kind: PersistentVolumeClaim
        accessModes: ["ReadWriteOnce"]
        hostPath: { path: "/home/mp281x/storage/vaultwarden" }
        # storageClassName: local-path
        # resources: { requests: { storage: "1Gi" } }

---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  selector: { app: vaultwarden }
  ports: [{ port: 80, name: vaultwarden, targetPort: 80 }]
