apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vaultwarden
  namespace: app-ns
  labels: { app: vaultwarden }
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/match-tag: "true"
spec:
  replicas: 1
  selector: { matchLabels: { app: vaultwarden } }
  serviceName: vaultwarden
  template:
    metadata: { labels: { app: vaultwarden } }
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:latest
          ports: [containerPort: 80]
          volumeMounts: [{ name: vaultwarden, mountPath: /data }]
      volumes:
        - name: vaultwarden
          nfs:
            server: "10.43.0.140"
            path: "/nfs-direct"
          # hostPath:
          #   path: /home/mp281x/storage/vaultwarden
          #   type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: app-ns
spec:
  selector: { app: vaultwarden }
  ports: [{ port: 80, name: vaultwarden, targetPort: 80 }]
