apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: app
  labels: { app: vaultwarden }
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/match-tag: "true"
spec:
  replicas: 1
  selector: { matchLabels: { app: vaultwarden } }
  template:
    metadata: { labels: { app: vaultwarden } }
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:latest
          ports: [containerPort: 80]
          # volumeMounts: [{ name: test, mountPath: /data }]
          volumeMounts: [{ name: data, mountPath: /data }]
      volumes:
        - name: data
          persistentVolumeClaim: { claimName: vaultwarden }
        # - name: test
        #   persistentVolumeClaim: { claimName: longhorn-vol-pvc }

---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: app
spec:
  selector: { app: vaultwarden }
  ports: [{ port: 80, name: vaultwarden, targetPort: 80 }]
