apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: default
  labels: { app: vault }
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/match-tag: "true"
spec:
  replicas: 1
  selector: { matchLabels: { app: vault } }
  template:
    metadata: { labels: { app: vault } }
    spec:
      containers:
        - name: vault
          image: vault:latest
          ports: [containerPort: 8200]
          command: ["server"]
          securityContext: { capabilities: { add: ["IPC_LOCK"] } }
          env:
            - {
                name: VAULT_LOCAL_CONFIG,
                value: '{"storage": {"file": {"path": "/vault/file"}}, "listener": [{"tcp": { "address": "0.0.0.0:8200", "tls_disable": true}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h", "ui": true}',
              }
      #     volumeMounts: [{ name: data, mountPath: /var/www/html }]
      # volumes:
      #   - name: data
      #     persistentVolumeClaim: { claimName: nextcloud }

---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: default
spec:
  selector: { app: vault }
  ports: [{ port: 8200, name: vault, targetPort: 8200 }]
