apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: app
  labels: { app: vaultwarden }
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/match-tag: "true"
spec:
  replicas: 1
  selector: { matchLabels: { app: vaultwarden } }
  template:
    metadata: { labels: { app: vaultwarden } }
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:latest
          ports: [containerPort: 80]
          volumeMounts: [{ name: test, mountPath: /data }]
      volumes:
        - name: data
          persistentVolumeClaim: { claimName: vaultwarden }

---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: app
spec:
  selector: { app: vaultwarden }
  ports: [{ port: 80, name: vaultwarden, targetPort: 80 }]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden
spec:
  capacity: { storage: 1Gi }
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: vaultwarden
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden
  namespace: app
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 2Gi } }
  volumeName: vaultwarden
  storageClassName: longhorn
