apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: app-ns
  labels: { app: vaultwarden }
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/match-tag: "true"
spec:
  replicas: 0
  selector: { matchLabels: { app: vaultwarden } }
  template:
    metadata: { labels: { app: vaultwarden } }
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:latest
          ports: [containerPort: 80]
          volumeMounts: [{ name: vaultwarden, mountPath: /data }]
      volumes:
        - name: vaultwarden
          persistentVolumeClaim: { claimName: test }

---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: app-ns
spec:
  selector: { app: vaultwarden }
  ports: [{ port: 80, name: vaultwarden, targetPort: 80 }]
