apiVersion: v1
kind: Namespace
metadata: { name: vaultwarden }

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vaultwarden
  namespace: vaultwarden
  labels: { app: vaultwarden }
spec:
  replicas: 1
  selector: { matchLabels: { app: vaultwarden } }
  serviceName: vaultwarden
  template:
    metadata: { labels: { app: vaultwarden } }
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:latest
          ports: [containerPort: 80]
          volumeMounts: [{ name: vaultwarden, mountPath: /data }]
  volumeClaimTemplates:
    - metadata:
        name: vaultwarden
        namespace: vaultwarden
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources: { requests: { storage: "1Gi" } }
