kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: app
  namespace: argocd
spec:
  description: app
  sourceRepos: ["*"]
  destinations: [{ namespace: "*", server: "*" }]
  clusterResourceWhitelist: [{ group: "*", kind: "*" }]

---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: "ghcr.io/ajnart/homarr:latest,vaultwarden/server:latest"
    argocd-image-updater.argoproj.io/auth-server.update-strategy: digest
spec:
  project: app
  source:
    repoURL: https://github.com/MP281X/argocd
    targetRevision: HEAD
    path: app/app
  destination: { server: https://kubernetes.default.svc, namespace: argocd }
  syncPolicy: { automated: { selfHeal: true, prune: true } }
