kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: blixter
  namespace: argocd
spec:
  description: blixter
  sourceRepos: ["*"]
  destinations: [{ namespace: "*", server: "*" }]
  clusterResourceWhitelist: [{ group: "*", kind: "*" }]

---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: blixter
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/mp281x/blixter-frontend:latest,ghcr.io/mp281x/blixter-jobs-handler:latest,ghcr.io/mp281x/blixter-cron-jobs:latest
    argocd-image-updater.argoproj.io/update-strategy: digest
spec:
  project: blixter
  source:
    repoURL: https://github.com/MP281X/blixter
    targetRevision: HEAD
    path: k8s
  destination: { server: https://kubernetes.default.svc, namespace: argocd }
  syncPolicy: { automated: { selfHeal: true, prune: true } }
