kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: demo-argocd
  namespace: argocd
spec:
  description: apps
  sourceRepos: ["*"]
  destinations: [{ namespace: "*", server: "*" }]
  clusterResourceWhitelist: [{ group: "*", kind: "*" }]

---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: demo-argocd
  namespace: argocd
spec:
  project: demo-argocd
  source:
    targetRevision: main
    repoURL: https://github.com/MP281X/demo-argocd
    path: .
  destination: { server: https://kubernetes.default.svc, namespace: argocd }
  syncPolicy: { automated: { selfHeal: true, prune: true } }
