kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: infrastructure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    # argocd.argoproj.io/hook: PreSync
spec:
  description: infrastructure
  sourceRepos: ["*"]
  destinations: [{ namespace: "*", server: "*" }]
  clusterResourceWhitelist: [{ group: "*", kind: "*" }]
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: sealed-secrets
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/hook: PreSync
#     argocd.argoproj.io/sync-wave: "-5"
# spec:
#   project: infrastructure
#   source:
#     chart: sealed-secrets
#     repoURL: https://bitnami-labs.github.io/sealed-secrets
#     targetRevision: 2.7.0
#   destination:
#     namespace: sealed-secrets
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     syncOptions: [CreateNamespace=true]
#     automated: { prune: true, selfHeal: true }

# ---
# kind: Application
# apiVersion: argoproj.io/v1alpha1
# metadata:
#   name: infrastructure
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/hook: PreSync
#     argocd.argoproj.io/sync-wave: "0"
# spec:
#   project: infrastructure
#   source:
#     repoURL: https://github.com/MP281X/argocd
#     targetRevision: HEAD
#     path: app/infrastructure
#   destination: { server: https://kubernetes.default.svc, namespace: argocd }
#   syncPolicy: { automated: { selfHeal: true, prune: true } }
