kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: svelto
  namespace: argocd
spec:
  description: svelto
  sourceRepos: ["*"]
  destinations: [{ namespace: "*", server: "*" }]
  clusterResourceWhitelist: [{ group: "*", kind: "*" }]

---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: svelto
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/svelto-software/svelto-frontend:latest
    argocd-image-updater.argoproj.io/update-strategy: digest
spec:
  project: svelto
  source:
    repoURL: https://github.com/Svelto-Software/svelto
    targetRevision: HEAD
    path: k8s
  destination: { server: https://kubernetes.default.svc, namespace: argocd }
  syncPolicy: { automated: { selfHeal: true, prune: true } }
