apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: oauth2-proxy
  namespace: auth
  annotations: { kubernetes.io/ingress.class: traefik }
spec:
  entryPoints: [websecure]
  tls: { secretName: auth-cert }
  routes:
    - match: Host(`auth.dev.mp281x.xyz`)
      kind: Rule
      services: [{ name: oauth2-proxy, port: 4180 }]
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-cert
  namespace: auth
spec:
  secretName: auth-cert
  dnsNames: [auth.dev.mp281x.xyz]
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
