apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
  annotations: { argocd.argoproj.io/sync-wave: "-2" }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
  namespace: tailscale
  annotations: { argocd.argoproj.io/sync-wave: "-1" }
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  - apiGroups: [""]
    resourceNames: ["tailscale-config"]
    resources: ["secrets"]
    verbs: ["get", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
  namespace: tailscale
  annotations: { argocd.argoproj.io/sync-wave: "-1" }
subjects:
  - kind: ServiceAccount
    name: tailscale
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
  namespace: tailscale
  annotations: { argocd.argoproj.io/sync-wave: "-1" }
