apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-config
  namespace: tailscale
spec:
  encryptedData:
    TS_AUTH_KEY: AgCI1mAWOP7DrTAd6XoYf761ZpYF+Yus4aJiYoCoNfBRPdEaN9DZh3ENQx4Xsq9SE6URRfogDsyrRaBrrw+6EStmlGxuoW6OuOVs11xB/CGJN6IjQAK9UPWUtuepFk+c0C1fv3cuAWadpUPwjEGof2diFEPoa9ykJR0VnHtx+h13bHBhnfQo2dtuxpurgj8WiKQlj3wHAbasASWoptj+vzL5bIPUZ2gaEi9s+ZTVAjwpdE8Ikr3Kw/tKn9jXNw8J4hfiWsZG3f6PA6EgMRUPvPabKFfU195zEN+q6bBUWcKGRdSjOMyQKJGI4TWbObaz9N/hOOAOw1rzPqVRX/GakqRb18nbFFUoaEWSJH5nqDtl1sant1xIRSplZWVaiDTTkwHTRVHWYQWjc8La4ZpaId1BZrTAdKNRpBlExRKX4r3InfbgnopgruJtjP9TxY7PQxusGt/7/6TdYteFJ+ZtlJML/oplWXmszDIKDkqfzRCpg18v1Sbn68ZWsJ9SoeUtleH0c9yiX8fn5nhWK+R7ANiAP2t2Tm8ZwSbiNe+fpB+mjnSE7Dh2yWecmtB+4u1oXtHl+tj/IwT3o807EhqXDlaZtiEk+1XdGOsm1mdMtlIn+KrPl0hw0znanCwDnh5zQYaU+byHP3HYhFT81DKof/GMvkiISb1Id+fSex/v2qPVkfzf/N20U+uYazdXgYSy5cOKHHIQfhVd0wQYpJ1kKmLUMftwCIw9r6roUqvxsKqcxW3lB+wwJ93RzCyKZRoaNoYavoAxzj1DGQ==
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-config
      namespace: tailscale

