apiVersion: apps/v1
kind: Deployment

metadata:
  name: tailscale
  namespace: tailscale
  labels: { app: tailscale }
  annotations: { argocd.argoproj.io/sync-wave: "1" }
spec:
  replicas: 1
  selector: { matchLabels: { app: tailscale } }
  template:
    metadata: { labels: { app: tailscale } }
    spec:
      serviceAccountName: tailscale
      terminationGracePeriodSeconds: 60
      containers:
        - name: tailscale
          image: ghcr.io/tailscale/tailscale:latest
          securityContext: { capabilities: { add: [NET_ADMIN] } }
          env:
            - { name: TS_USERSPACE, value: "false" }
            - { name: TS_KUBE_SECRET, value: tailscale-config }
            - { name: TS_DEST_IP, value: 10.43.0.100 }
            - { name: TS_EXTRA_ARGS, value: --hostname=tailscale-ingress }
            - name: TS_AUTH_KEY
              valueFrom:
                secretKeyRef: { name: tailscale-config, key: TS_AUTH_KEY }
