apiVersion: v1
kind: Pod
metadata:
  name: tailscale-proxy
  namespace: traefik
  annotations: { argocd.argoproj.io/sync-wave: "1" }
spec:
  serviceAccountName: tailscale
  initContainers:
    - name: sysctler
      image: busybox
      securityContext: { privileged: true }
      command: ["/bin/sh"]
      args:
        - -c
        - sysctl -w net.ipv4.ip_forward=1 net.ipv6.conf.all.forwarding=1
      resources: { requests: { cpu: 1m, memory: 1Mi } }
  containers:
    - name: tailscale
      imagePullPolicy: Always
      image: ghcr.io/tailscale/tailscale:latest
      env:
        - { name: TS_USERSPACE, value: "false" }
        - { name: TS_DEST_IP, value: 10.43.204.239 }
        - { name: TS_KUBE_SECRET, value: tailscale-config }
        - { name: TS_EXTRA_ARGS, value: --hostname=tailscale-ingress }
        - name: TS_AUTH_KEY
          valueFrom:
            secretKeyRef: { name: tailscale-config, key: TS_AUTH_KEY }
      securityContext: { capabilities: { add: [NET_ADMIN] } }
