apiVersion: v1
kind: Pod
metadata:
  name: tailscale
  namespace: tailscale
  annotations: { argocd.argoproj.io/sync-wave: "1" }
spec:
  serviceAccountName: tailscale
  containers:
    - name: tailscale
      imagePullPolicy: Always
      image: "ghcr.io/tailscale/tailscale:latest"
      env:
        - { name: TS_USERSPACE, value: true }
        - { name: TS_KUBE_SECRET, value: tailscale-config }
        - { name: TS_ROUTES, value: 10.43.0.0/16 }
        - name: TS_AUTH_KEY
          valueFrom:
            secretKeyRef: { name: tailscale-config, key: TS_AUTH_KEY }
      securityContext: { runAsUser: 1000, runAsGroup: 1000 }
