---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: teleport-https
  namespace: teleport
  annotations: { kubernetes.io/ingress.class: traefik }
spec:
  entryPoints: [websecure]
  # tls: { secretName: teleport-cert }
  tls: {}
  routes:
    - match: Host(`teleport.dev.mp281x.xyz`)
      kind: Rule
      services:
        - kind: Service
          name: teleport-cluster
          port: 443
          scheme: http

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: teleport-cert
  namespace: dashboard
spec:
  secretName: teleport-cert
  dnsNames: [teleport.dev.mp281x.xyz]
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: teleport-kubernetes
  namespace: teleport
  annotations: { kubernetes.io/ingress.class: traefik }
spec:
  entryPoints: [tp-kubernetes]
  tls: { passthrough: true }
  routes:
    - match: HostSNI(`teleport.dev.mp281x.xyz`)
      services:
        - name: teleport-cluster
          port: 3026
          terminationDelay: 90000
          proxyProtocol: { version: 1 }

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: teleport-database
  namespace: teleport
  annotations: { kubernetes.io/ingress.class: traefik }
spec:
  entryPoints: [tp-database]
  tls: { passthrough: true }
  routes:
    - match: HostSNI(`teleport.dev.mp281x.xyz`)
      services: [{ name: teleport-cluster, port: 3036 }]

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: teleport-ssh-proxy
  namespace: teleport
  annotations: { kubernetes.io/ingress.class: traefik }
spec:
  entryPoints: [tp-ssh-proxy]
  routes:
    - match: HostSNI(`*`)
      services: [{ name: teleport-cluster, port: 3023 }]

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: teleport-ssh-tunnel
  namespace: teleport
  annotations: { kubernetes.io/ingress.class: traefik }
spec:
  entryPoints: [tp-ssh-tunnel]
  routes:
    - match: HostSNI(`*`)
      services: [{ name: teleport-cluster, port: 3024 }]
