apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: monitoring
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.50.0
    helm:
      values: |-
        # admin:
        #   userKey: admin
        #   passwordKey: password
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Loki
                type: loki
                url: http://loki:3100
                access: proxy
              - name: victoriametrics
                type: prometheus
                orgId: 1
                url: http://vmsingle-victoria-metrics-single-server.default.svc.cluster.local:8428
                access: proxy
                isDefault: true
                updateIntervalSeconds: 10
                editable: true
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: { prune: true, selfHeal: true }
