apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: monitoring
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 5.2.0
    helm:
      values: |-
        loki:
          commonConfig:
            replication_factor: 1
          storage:
            type: 'filesystem'
        singleBinary:
          replicas: 1
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: { prune: true, selfHeal: true }
