apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: monitoring
spec:
  project: monitoring
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 59.0.0
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: { prune: true, selfHeal: true }

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: traefik
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`grafana.mp281x.xyz`)
      kind: Rule
      services: [{ name: kube-prometheus-stack-grafana, port: 80 }]
