apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tailscale-cert
  namespace: default
  annotations: { argocd.argoproj.io/sync-wave: "-1" }
spec:
  acme:
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
