apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: infrastructure
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.11.0-alpha.2
    helm:
      values: |-
        installCRDs: true
        replicaCount: 1
        extraArgs: 
          - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
          - --dns01-recursive-nameservers-only
        podDnsPolicy: None
        podDnsConfig:
          nameservers:
            - "1.1.1.1"
            - "9.9.9.9"
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: { prune: true, selfHeal: true }

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tailscale-cert
  annotations: { argocd.argoproj.io/sync-wave: "-10" }
spec:
  acme:
    email: paludgnachmatteo.dev@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef: { name: letsencrypt-key }
    solvers:
      - dns01:
          cloudflare:
            email: paludgnachmatteo.dev@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
        selector: { dnsZones: ["mp281x.xyz"] }
