apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homarr
  namespace: homarr
  annotations: { kubernetes.io/ingress.class: traefik }
spec:
  entryPoints: [websecure]
  tls: { secretName: homarr-cert }
  routes:
    - match: Host(`homarr.mp281x.xyz`)
      kind: Rule
      services: [{ name: homarr-server, port: 7575 }]
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homarr-cert
  namespace: homarr
spec:
  secretName: homarr-cert
  commonName: "*.mp281x.xyz"
  dnsNames: ["*.mp281x.xyz", "mp281x.xyz"]
  issuerRef:
    name: tailscale-cert
    kind: ClusterIssuer
