apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: default
spec:
  encryptedData:
    api-token: AgBHO/pHPtoOJmNWca+GuttSXsU8lJ5dAkbtBjiPXlOL7ypYtkgP2vy8NvAmmm9lFzX7+GyxFKaE/Tt8UyLmlb2ruh6UgrT5UT6iCNzDeQ0wrqgQ6c4ph6QDODFEBuu/aEuDaDFogdBKl1kS5nLN0lL6YsObwy/5JRfYIwPqUGEFoUYbZQ+Rgxd3kLaymneUWeCnI81pgfbLTsERfPq3KvP1ZFXeuZvrLEm6ouAvOVgzil/q8AEutKXQS6GnPkTxtcPMybKYkugu2xBfh6CleY5QANyCF/YmleVsLpWXcm0EvdPkjTA5VZFrc+Nb3CmKFbjXAPF/Z2bcilTeiNyB4aEs9wcxTwIeAnURHdNeAQ2l14C6DnkINGHv1JawcNUyFC/SBL4u84ViSSQQlx3JNOngw3xfjmfGjuggti0Ih4ZkLgsKmp6pfWYJ2ybW0BVH2temp7PgbluwwJdQtkqeo3Pl+dRrhRSxTJYzPOZaNbj99H4wSTVkB1oEjGVBxmTa0LMd/+p6g3tph2xI47dI7LLHAw4faSo4Hm77LgcqW28ISvZD00ASro10QCH/VIhgVyJICp28g7AZ4KoWOY47Q2tl9H8IK0pQFeb1Hgemxi0p4QiEF18ziSoeI2HEX7IqQR84qqtn5nTMffp2P//k7LBzr7AJ0aQHPnCsex84XQEtiNGvzhbqVWzQxRGEHn0h9CcKEwbVLIdTveNXhTAyJN2h7mMSOuaQ1L1GKEQAbPPmyTKJ8S2SZ+u6HHJAjJ2/Z8fd2sLzqxytTA==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: default
    type: Opaque

