apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCYPKxHeQ9j6yIlifeFDMqOUVK4yFBXb2gd3VzYX+A5DltLJ4vdEGr5QU8rzz9LfARclYchsdJmQwXKeHwKxSBWchA0fuGl2AP7FSd5kvcn5UFGELCV+5IQbqlScAv+WtQy8t0NwpqhZogYR+Udn4Qy0PrGh0Gp4JYxNLX/WLQt/c6uddmjwCFvEQcDpxS0zNTRvuSIkZjkcEfY7zZ3pgkLvJxsV+M/k6Uqx0kMZXIvCdpeB5x0iYTEzriOiT7sJC+x/VK2Mib45kWSOm1dGz77hCpzb1Ij9KjHnzR2MigabLN5uELf7lMgvPylZ/WdlUkcyYvxzCda6TLT9blX0haBjkLbx4gdXI2vaMINuqfnLSNYdZmI3DM7JuVleITjPlQMgdg5WLG/+dqJcXjP7KYtOFZ5uuw8bTQhspAtZ1k65GIdynCyaf1QEoXmw/5BmF9RD/QP0oTk3jiyJojJRRgVpmBQRlLWlHLS+M4R9zixIgGPMNbc4OQ9FEuR7GZZQN41h8+xvFmyDmM7m2v7csPyGAuXeWusB8tJ0CLKU8CcuacqRFalE7nYkeYaxK90DJSeE4fJeLBbjBOAjHnSx8I2aIRdUok13tRDb9CnlHX3Ach4e3EbOiUuC4vH854DNv1a5EiAHxo8ec9N7WdZYzLNyCTmru1QnAjQYUxDG1Cwc6LqE/OgVjquHIbvo48VBT5jlO9I/5aKYRPFi6pFettetddRDv7g+zgDZxe9sCKqXJrycDF5k/a++ZC4gY7zmrSh99Y10oeLRQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque

