apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgApzMNrUyGT9PV/jef6Z2waYHOIjFJLOjUqobknuNduY3ncq8j3WVF1ToVph1RONp9JBIwbyPJhLugMH8uKIQrY0tHETxStFw6G7GnTmp20JhwyXM6NGEwFLcpB9X0pjr4WtzvBQRq2eD5Y7ZGULJJz2Lf+LUe9JLHkHkhBLUWQAQ/bRj1ZwnOcaee1NYzl8NPYa6DqRviWxO742gPisTb7r9Q/TKriFB6thwUhl99KCPxQDamT0c3H1Ye71tBqGwiQWLdoZN3Ah/wZSK1Qv8v0Ol8J/0sxro/93xEq1FxUwH9uI4pSJfV60llB0ZlN393eGCpA6oUu9s6R322dHGal74wa6BUoIn+CyLcABWQ1FMlkCbjHbx0Cq9Ptpf/vJPGT1jOHqPXQ9zCAdXfSptGd0R0EPlR42HjbllLjd1J5Tkv3ujD2cZ0VLselVhQmSvbwAKDybwmOjjGyp8aF99kBRH83SvGJzffZ6x02KMRfP1qpEmoFzo9DeAIje8ED+oxexStFTVBJmxChhYbcf+fRzO0wAOSVrfiRKXUxYFmxRihhGn7mJCR+kSMFc8609pYINupQNkjFCGinAkuKMTElbn6X9bvaRisfWr20R/LcsvgFOrs2C9IxDkWf6aT9OZJ/wWb+z7iXvaNYemmJDyUDlGMK1guIPnX7T06t21r2WGLZ6/8lYE/NBals6P3XRpPOeq72j0B1xzIs1HIm5TAXHVypniScb3A1KfVf9jD0E2MKzjK1Ix4C
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque

