apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCHYOEhw50O6QfrCdr8UbpzHFgkvY5Yumozc+YfrqIPb2t31JKA2EJi0/sC3mpgxheUhAzQkVXGUz8NNQD6NMA14moSvBe3trOwG10Ruy7HuGhJGuODh/q64GK5GZfHt2dsD57amPbduOyGAgYp+2vSkbxJuZkKzGwbIKPxslCa637ir5MFCXH6LTadFxmDXOIk8/OU3wxh27xdYWayJnOLZzrJL9VZr9wFg5NnLL+ijV//d7IZVpCn6/LDVp53K+izHSZc3otEHP9kw/xhNWZNx/C8QRSfXTU2Q38C1ka6Cqkeqn+St4zA4FGMMMouwMhlp+efuTtAr6ez4Ekhv/mlrqQ/u6wGYANTy5O1s77g46pWZ4Qqjc8/zKR+o6micEtAVKUFrG1Yh55pUbbddGJtOZsb+3u8fBHHazd0QpI5wkUSfuqhQkLlquYp/I1we19MqRwFl9KQ60H6mSOTGUGDDusrw1thpALML4qLoyfRUSypEJQWgPPRB7RKlLHR+i6aTwdjzNaGqQCNHv6Ko+vNwA0asGeKFHaRQLVaxpN8zw8X2ZbbFbgi69pZO3rszKMqFQICBl8sj85j6bxIuYxHx3ES9TAJD6zf/3N2YZutU8C6iJF4nTMdZAcOgVL2fmW2rSImK/uf1wGB7FT8dK4RPhM6jFgR9S5nkcJdQxj76q+7AT/AjcZ5Z2msqdZXc7VsrDvq5KkPuMi7GiG6pw3T1eujuwTktJ2UCsjdEA26NdVvxmCgDytkZSlJ4a++9wXQ6l7KCWlSeQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque

