apiVersion: v1
kind: Namespace
metadata:
  name: actions-runner-system
  annotations: { argocd.argoproj.io/sync-wave: "-2" }

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: argo-runner
  namespace: actions-runner-system
  annotations: { argocd.argoproj.io/sync-wave: "1" }
spec:
  replicas: 1
  template:
    spec:
      repository: MP281X/argocd
      env: []
