apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: argo-runner
  namespace: github-actions
spec:
  replicas: 1
  template:
    spec:
      repository: MP281X/argocd
      env: []
