kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: github-runner
  namespace: argocd
spec:
  project: github-actions
  source:
    repoURL: https://github.com/MP281X/argocd
    targetRevision: HEAD
    path: app/github-actions/github-runner
  destination: { server: https://kubernetes.default.svc, namespace: argocd }
  syncPolicy:
    syncOptions: [Replace=true]
    automated: { prune: false }
