#? Github actions 
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: controller-manager
  namespace: github-actions
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    github_token: AgBK81fHR4gI4NTqHuWqe+YlqFbcUX1pXWeGBjARkSGB1DWKOPJBxtqLlflsjAxoLIZaTC7wJTpK/TwgkK+YaDXSbZJeGLCFVJHyv5sQ8HrgOsdpb5u4YT0QGnfAcj4dGgOxvFeSwROjWEDNxvYldNCC5VYjv1urbgDfAuUC4k7j9dpaYQfaomTxrzViEUw6AEzvlkL9V869hU27fhFlzMZResOkVpW96VKiVrn0UNUTGQbNffaQ6Uwu0zxkgwaaqnpyZjMGtq0bpMLlpxWs9i304cAd7cjbt1vA7Z4Q+aVA5Th79t2Pj7YgzzbZrDDJSSG2MQ0MlpqqWD7Wknx1MfHxVbJNCP85xwL3deFxx71rGjw+bR6ynqLxxFdOpYqFMZv4WabkRhSZM3VxaLspvwENYkjXMhXso2GvxktXFILG6m9PC+X0d7Yq8I4K+iZNmqDp20vYCi3DX/80ERGbT3Rjt0eaf+n3JVnILwcStheaRSJ19fDGGkYQ1emj+7f20iPNvGj3Jikq9wk6jJXCjx0dhPqpLIo2yuggMG1FxVZ8menuzFg9hW8OD6kbvW5KerIT6f88EJapkOKLDYSESaXS5z1/7Y6n/63AvzlJ/N5beOpdGEUFG4o8D+h24WaMrtX4h5JOAbWGZ5dmXhl6nByU3QJaCjuul+p/OgS7dNC6HECw893ixJD4vGpCpFt7lh8EpJ5tnHd1NsatSgFdwb7ubScYyZMviD5dZyNXTP/Rw+84UcwhEHc9
