apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: github-actions
spec:
  encryptedData:
    github_token: AgBgkCktmONKf+tcozbaard7AA8Kgi2kblsMAZsD2fH+U5HXf8X8Q1+EOlzEwA0NDOtPUNZVAC7aTcs5Pl5289Se5T8BroeMwqxfUxKfn2pU3srJtDYQkEXXn5KZdBeosyghZ2JKWa8Zk1Ph62b/0BQm2rZji2036qghy71xyRbQaDW3o1+lMDZAsGoD1uGWcP2RQhn6QHSfXD9BcU5zy4SLRonWXG7z8Rwsc57gwAHiRG0t3SfSRenfWQG3416uoELivxcXN8Gm4v38HxoAF05iSYPGezVhM18f9nTpKjLBiyyeBts+Luvy0J5N7JwSxWFRBrIHBcm8e5cMSbOt56ZQ/vtQ8SI7gt3WiKl5Y45Y0hq8777nGQAT9HTXh9Mt6MrmLNGKvX4VEv3Ce+DJHcNYKklNod+sP6QeIkFbd19qHTPuZLd65yii6U5t39BUQ4/Jk6Jlu+6tSRdS/d2r6aNlmA+LhJX0kcgMt/KuTS5r6cVdr4ofGbjACncCSdjrrSVe+kCZrL2jnaArWrVSL63XKZ7QorpDq/rQ7uzyKNl0GaswCjAbnWMVIYAhn03r/6EJWFd+eB4/b63OCp0+CpNSzsgC+AvzLZqxerrw7odFlFGBgIBcY677UkohqRMhv+uoA5vlyCgGV8A58hLrFP1a8SOIulxkWRrykCd5z+YvoJYuT+znODADHKsoofJDU2wJEEqDsg28hqrKaKhAlIJP41aCIU0NkFwcBfQrU1bEc6eqUEKA1Db3
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      creationTimestamp: null
      name: controller-manager
      namespace: github-actions

