#? Github actions 
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: controller-manager
  namespace: github-actions
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    github_token: AgBNvE+wWNB69+5vo32hncJzTDKVOGZJ8ClCObqXiwSgijCNAxcnfyfBbsNvIwyBiYH2xzmtMiu0kxw14vMSaMdE2nHDXm0EHwdNPd1s6XL2HC/7Y0Z0pt9oAKGG8KTir8DpiRdAb7Oh8cOgCouxRRNX+Fq/Yp8+mlepWP3bl+OgyLNTAnEYLeFaQBbXvmbLfrJ8s9+EoDFUdZsrl4HaRNopgTmSSOMezDYgl8JfZO4wKagiE4nNMRdjICf2miezDfvXCIt76SGv/yMXysEf/CNYqo66YqZqGkfsPHh4Yro19hbDINb1HbYytLswvhSv4/4HwB/WdRVFtDn2KDJ3g38evKHBF8Xyh0aPq1W25Xd3fvsnGw66j0gVZ3VGbYiF5aFQucg2SigEFyjxOHBw2gFrmWzLbEU6+sWv81KgMzo0v9BQ3vxrN+CkR78gfqriQduxWpL6GMv8JFtZIQJvZ9gHGEyrVawu1BZb1C57Zz5KmFgcgrPwyzV4o8bYjH9qKkftvqKucXmYe/C5IoggUKBZSiAOgfel/OoeVvKQKpuyKTodyS+vxdDt8YCwvaEJ//OA2YFYOPXgtNS8VBYbH5pSGoddpzYnHGPi1UflpkIgtC1bT66TkL6bqLQGAMy0+JQFM+Jndu2uHcg35j288mxdQdnJQ8c2FArLYQSxOBPaYAbPSKUua3zhPRKDw2WvYgPteEz/sjQa4hbkdL1I5PMnferOozah0UPf9lB0aiJ+Q0sKU9LTrEUR
