#? Github actions 
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: controller-manager
  namespace: github-actions
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    github_token: AgAjwrNkClZAZEf4h4ty6JK3b3ySDKEJLbsSp0rvSgrKlTSYsEkMvAa2JX/4rpeh3ZUrDSVRcHORpYTEIGEP8d85yHCKtKI+xIfTyPoGIlLdH9x0Pi9yLV/HDMvLv8+K55GmeZ9P70OChACxCPGesW9GNPjCsQpjE63qRjnlsAUI/0J+lu3OsUfNVQBav0QnM1TeEOglLC2XWVaj8/IjwN30DRVMnBXjWwjSKdKg4cEfao1Z+/pJtEuWdiNTg1Rmptu+MaebWpSSM17ZCo4Z2OHLy+ZR6m9N/5vZhsFlHSF9r/zjy9gr75IyNrE2yj8jTCay9ZuFoyoVXGCKUue7ldNg8xl3Qi1cKVvvCEO2Pe7DHCYASRWHLx3Qe+cYbjmnAq6HVXiqJiAE7AtHQhYCCDnQVQy+UJXJMjQYTr9AsACzuGh81CE6PVUC7akkU3t7DkY11CJ2M+IF+QpDFSicfpTptkYX2oRSWVNauEcLhbGlbhrlwFQ0kfnH2xaajP/JpMb5VTNokIFq94pn6tmMuOq4v2Ws0uIUYKfOl6HNS5/WfxMbfKUBkRrdmp6GmoLefzUjaxck31pz4l4ri7PV+ysy+mbuYj+KUbULftiYlGIiyvvm6cSIvTrttI25DweZDiFU53yh5x0tks/zKT/Jrtrfuj19jTV8npn0hagM+6AY7dtlXVruA7Y8F1zWxpkjDGQoOkqMqiY3E5zyywAS5Ii/J5DHmzZiAug1VhRTFM8F1mKHrBxdydDp
