apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: actions
spec:
  encryptedData:
    github_token: AgAZ/mjEbmv5upm/z68T367Ayi7jVrdnVBDo7Ryh+lh18tSAb/3D/jh4NIsXW7FNN6KsZyMD/J2nJDMRTHatINA2kZ8ahKHwGruV857jf52vMw8RpEFCAOcchDbaiDjioBEUfTv8CXAGhHF+kjjFCWURrjJ2s2QxSD/mwB199N++6vp0lB/8h7wLWycg8kS3faYwIpVBLzL9NctLSTiZpB79ACkJEMy23piXGo50FiwPk+j2TkReO8dbcnw/Ku7UT5S2fEq8lv20vNUmbRJAqAZI2Tw/ArcadSg162igJnTfesy5bo4gWROaExf8rRnCLUaOSGrZMscPMO4vaAQhbbc0mG6lYjpqeuMmJEKURewP7SdHqMl485b7FDn9rKdt9Pd8tfnvXgqarV6K7oMCc+pweCx6Ocaoy7mu0/ZVtMG1lsX6RSXpTe/R/DVtF3OEPCcGRgQ9VZlHr+tzMK8nwGe4AJAzE9gE+EkHu7vpeATDlXkYrIdqOTanzEuayda7O/RB7RV9E2MW2kdwQ9GATTzLjCTVASK7P36Qh9uz/FyRib4FFpNIYx7XXeA/Lwg6Uw98QM6LrVND+j7BnVS1AM2IIMIioCvGy1OA3aw1ToGWhosbT9lofxskw1pjhbGAGo6DtwqUihcdy/z53yoJRQlXyA6JMkAqUc18RXR1cNO4oewSN+V1HLALw6z+fFvsIeBsyiEZKxnuJhsuEMSr0OCIAx7c79W4qlOZ0WzmYdXLeHhh936yLl2M
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      creationTimestamp: null
      name: controller-manager
      namespace: actions

