apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: github-actions
spec:
  encryptedData:
    github_token: AgBE3SHBBvTph7Tk4MpPKpog661Z0psOG5k4QsWdox9r3ag1k72ZTPB7WwTAU5Uy9SvYNB5boUEtZWtta+UmHgUqQblnDmbBEtXn09nNTvfmE/rH2O7mI8dX/mINzJcW0GwK4wb2ftBdaMQVOPijpkgmV9rjdnVMkaHmj8HgEff6HEWXdEwbZna52diT1NnjUmW/maY/OoS5egKMuG/rtYEb47K8rEnlmGryPkaIQmywJXgxmXT4Gg2RZYvoDyrogWclZuSZqhXVqYxLZJhJ/Ss03u5DZs1NrNUTxQE+g+tNqNUV8hWF2wjVyL2qPhQtPwH+tdiPKtWZLZcoE0p7ZWQV/TPgQ4e5NywxupVnYuLxzo1Ps0zBtP2iOTkmZB40g8r/tT5j8wsDNjC7prMdTX3srgj2RIErgtNbvW1FSNoIbtEM3yEJtsnFsP7y3CyF+AFtSqn4zIlKT9IQyLAVgYgl95FOz+dt8vJIspeYHhoY0ZwczkiY1f5Vk4ZiM7FZSnkvIiYRflYbjq9FLUWubRsdoqFfEquDUtU2JaJXdXLYA08mcESD97duzC4pm6jErENaRhzgRP7dfO6f+qdDQEx6T8zDNcvf7mS/cJCrAi8CGIyOJZvMgbORpfLfNup3sQ5KkXSSixOWMxByWQn2JY5s/kLukzHslgXV4ooz3p7sIOa18pl7p9WWF5+QP0Ha6DyS0Evd24095cSgM3idMxVjyAbyC8EoeGBooHs6vuoiD++q68stbhMh
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: controller-manager
      namespace: github-actions

