apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: github-actions
spec:
  encryptedData:
    github_token: AgC4gM5bAMMpxzXOxKgQ65N9V6z+6qPnazH9U2O44RhXBki6UyIv8t4Se/vYFnWzmjgUBtprcrDGXpWjaqYsYK92S5DcA0KhFTHE2sOTPO2zjHNQC1bU7kj63BNVOTxEYRW3pvoeBhvXm9sY0+bZb3E1QC4cpBfVA1KdTG85zzf+5Wd78DXqW1n3zV2g6TUPUvE0N5t++Ob/AN7SGkVjxKlw1tL+uQSYDbF+DZ6NArSQxjHgapGEIS+C0Zm074DgzTJlg1D0WUTH2dzR5TbEi5fEEG4JcRJQ2lJx5umtYii3VlIplpXctpgYVWrMLJ51XkGkwyOC4MgLHn31YUBi56MU9g1MpaBDqYM5OQlEot0USBrdXSAc2qBq5rc1NO4XhCQAVPigSY2CwAVCJKb8BYHtelD8fdZdzhP2ZGFkattTdDHofSb4zh5CoUQpwf2/+4YFl19onoHoRtpw2o++jhzcp5WeENIjZ87IXL2qPZxbdAOvtNoNWF1S4SX9PY/0tqHS6nCNZLwOULbFfYmQnOoXuich7bSblqz0Wolj8OVvuLTIPo4eZKtp05DyZmBnoE6BfnzVeVdhV7sPlAm754gJtx83BBr0XbkypL5ChcFbpj6NjUlTusBGROORFCdsi5it9Ujj6AaRga7iRw8ftlKWPaGFl0fW7vLkRPRJm+TQZJNrj3RPjs9uES90QRhQZRg4AXsOJtRo0/B4E6C9Te7GhT+iK75rryZHL0VSDl9k70KXu3Pr2/m2
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: controller-manager
      namespace: github-actions

