apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: github-actions
spec:
  encryptedData:
    github_token: AgCbzDokfoItOpz2sEjPXAHBz1ZeIfq4N5A/shpDjoGv/rZBTDNBlbfAlXGsdwnOSmN+xstuu363uv/kZKGTzE4J8/nwkqbB3X39g5Wn2m2bZcyjx6EDyyI/z+S1VRPesEkwZoWl5zkawOzRiciqsV3WKws9zodQtwct5FyWVKGq7Iq8G8lBSc62H92SBBS2dUdKei53TPnFEYomLxU8I6kzepZNBPfCOuu57ecE8Z4qX+RVQxUDSzxgUJEKjaoUowchboxCpnT6NRakotwS0zmEGlKqk1E6R6yR8amy95V1QBqWbXgFVGytXUJX1aGu9E4XIEFC252B6IabHc+Yyl8rr4h/f/isVrH2Xu6EA/mt7aHWtt605c7YzRvT/Ac8BAF0PFvva0kSX1OWrdnMpZhf/mag8ZdJ7U8mB8zmOFKsi1mZUId1Yz6hrw8I5PLbT3Jrj2Fjc4ZsLhMCmuZtZslsxmR06XB8MOJVyGofgi6YQ9Z9hv0CmRN09VT+9Ll8O/12zQxon3ltllJMl6IiywMfa8llTVQbzH9wvO/edsFDOlh3cH+gjaWtneuuIk0MWVUsPgxItS91HVA4CbC0Wqo5FVGkUXRce/ZuONX0rQmBDzSkhLOvmnVGS39u4K8ehdJA85yptrJcCtH+PFl1b0cVTj2qhoG9vtyOwVzg6Mhsk+aZwVA+bcPTIarxeHvGjnyDTnpxuC9KUpbzQgClCqrVrazGxcZiNz8d3FraSyGGqUFUpDM3BfO+
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      creationTimestamp: null
      name: controller-manager
      namespace: github-actions

