#? Github actions 
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: controller-manager
  namespace: github-actions
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    github_token: AgAEaoBT46qtG+Q8ZRZChEcmFcT6b82WkWd8vK+93lpRWA5fl/nYt3tcjviKkfUh7Gn6OdiN5IqLbLh1IWFIWElvy+pRnMrBSygU8Xh61L2FhNjLEB+aSn4mGRk/teRZBV+dF22L7IRcd8yS/OZZdgERaWY1alsDvQq3+Je14fWOzlJ7pbTnXttqjKq9l7eZNmH8+Hvhx0LWzDTdSano8RYkzQgZeySE/SDhTI2wUDjoiIfmjB0x4+lgcUWyiRTY8MC9B66hrYWzxni9Bh867CvvyykHMHtu+sSrcOhFfZPLyBnAEgpa6BOA2hX3noZE35G0RMczz+FQbiEVY5Kiwo3dVk//AnlnpvitkyqDm/h7iJKLmhPtbWJpfrHdvCcVL6ozt1Kh2tSUKatffn5UrjrFeOPhkiaffX+IvdUp8SNGK62hy9xGaBPVdhxdVqiUeh4bcxgvwvc+TS8MyHjx3SwQUlTLtZR+tkn6dGf7UrGP15ZKSrJuD1kIhURUD7lqNMlJvgPgItsldsti8ut9yRO2WR9lz2sIJNhkCHIsJmPRJMi8+RBziVMQrMj1oIkpO4byqX89n8WAREZq1T5HTuBmy1tba1CyiXAY4C7X/89FIRjG3yTkkGYCrICAwHp2I3Y64oUlW98MwlWoJQr+zuz1N4RuswJwJl+BeHTbn1fZINcVpskqjRDJuVhQWZL7nxNHXrHJAkPylZ10EUYb1yquAC3usjGSGCjZrw9NLIdX7jVZRgEahPJ5
