apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: github-actions
spec:
  encryptedData:
    github_token: AgDAwZXr33zRsXEIs5U0JKSL+haiNWjDQJhb8CYYAOkkxhT5nbE+OsOS2W9Jq4TAxnDicU2nmrVxIufMgyNM3TeYj38z7hIAXoMTY7WJXPqGtU+SrfHVMRhcNnqx+GCpN5PM+TaYO0FnV1b9G9NIUwJHNFkcpOrpTMLeU/eztCzYGplQ6MdCjr1pvAQSR797nTjO/w/0kTOsIXAusnEOLoPwkJximBs1oPOpTcKLKR9UUws75CLNtEA14jklcbNrr0sslIV848L8pKXBW6RosYeNGBmnEZzC++dz7B2DjPIyWTmZLm7H2uH5mOpStY40oWUNdQcCWgsVk99bvsr2hXyLPpHD1aegmyABwB6I2w+TkoH01J/FfbynO/GCTboqGtlWQSSYnRHnMawMc4kAKOMl7bPl7Gvezty/ggs+4rUCDIlEayGx08Whr95t+5yEqyILybQweEMlwoyyeZfhUGJEgMTtCvR9PeF50SxQW+GvymzyYlcGxsgBnWmUWZAtVrXX/rYiuOGvPWcLaZWh9S+j6bOoyjdtcYHl7byIIAhFHJUTBmwZlLTlzNDgSUCNExZqoS8tOZ5mNmjIq4ZhtVUsrKZGJtd97eJyacGQ+7xM6fBNrRWyI/ThX0xtGJIq0jZNMsSJJQZZt3MPjTmrIQ+6/o/nc8UCdZkdQvo6yNJx8eqzUk36rBqMj57VzitxhFAYmOfnLMij6ufYdCZomnSvIEpWFxSz4Nvf3cpSr0ThfOcFDB+zVsq/
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      creationTimestamp: null
      name: controller-manager
      namespace: github-actions

