apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: github-actions
spec:
  encryptedData:
    github_token: AgBdMHjJzgw/aRXEZOhOPGWtmnyu0ZVDNbs9smPHWuEOal/dgOz/gUdL8NrGRFLWIShI1PWjyc/ORz/oLILI5YaAVj0gTHJSvgnCXXtnWDZksV744uHgi0Sd3fI1BcAXNaS+qR8uS1elj2uAozmSEasgP0BtsEe3frV654l/h21SLjS6SUL1eKDkQcZkuIW8E8lDhLdYr4GmvDDe56oN+8ozvyCe7yYifCTWEDIa/399iyCejSdXS5ZHzcCWl905qNzMonVZtOuJHQOJDVEywwcZZDxof6I8XY6OZ69oBL0U1tcYc6KGT4QDPfkl/cBHst636yw8ZG6HQRmCHQLnr4Ydrs1AgTC2CZ7JXqGb8gYrnDM4MpPC+RWsxKut1IU7HlNkcXRTdmpvbX3KzcmosAiwQRWjvvQz5Zn62nbAg+jPM30v/DtIQTkGqTE+VM9sWNLkyIZHVj3fYK+2keEaXQyh1htVcSVxhNmRcLfD9E9opk/agPLGibzQIadBRD4sFCkMTOD2tKvV0hmkjM1Ud9X90M5U8kOl4/lQVbhGJL9bL2n21RyXnzD0dq41ZWZSJrvWDY7z8YILOzGfKbHLztuSjJb5E9o7G8ikmSG4dqqGbphildGyiOr0P2k/AkzJXb4XZMFeie8cx2WmaaUmC/rlOwgMrAY1zcU8N0nnP+Des9mMVnUTZ6bH/t8f7BXKgPgkedRl/qh31QSold0Aniuv7xSBfXUAlQRLUIXPBPUVTR/byToPOLAB
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      creationTimestamp: null
      name: controller-manager
      namespace: github-actions

