apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: github-actions
spec:
  encryptedData:
    github_token: AgCZwImATvnCOMxzj205aTDQV4GKvrI0W1morkdYpCO0yEg2W4+lFfK/TnM+ZbfRWrpIMkFxPhERYEl34yMX80S73cQ44i5k/fG+OioZaKspoogDpET5JTLny4qZXapnHdggYhWLKJlZCQiuhEespyscWa1aQyK6ssdCFflUfw1tozEggENaxYN3sPiOuRbeLgrr5CMSaNlGpmSpQ1QqI8nxG6/O+mhljsB0rN5qoY7PRPECL6a/7lUv/C8ucG13VL+KYuods3cKyW5SV17xFt3cGZH/6AcHY2cxcbaeviMaL/v5IAqalruuLUDHM6VCvStjGc9g+zAWLh31RpI+UgOcqyBJ5HT3A8MiiRqWzf0/CxRJkNapmPqdwd2Qh6HQ1aGqhQm5c5G2IgG3/ZrAgSY1smdqSMAe4ua4AFhZlbXWjRgrBU91kbOntK5pAVC41jlB1i0/bw47iUKAXx5SD+60roIfGBmmibEXq+SEhuI1+utVPMY+f0UAblpqkPzKvX8lrnwdiJETpxZ8jUkbfK4WyjqGVBC1KkI1zneaThy1+zXPDanCaPMX73nL+CKIdGUFnWbBAJ9qex38dkJLHM3cYis9zqthWA3OhyGMPP+/seGmXBC6xbXHU89KIhFtTRXOjuyzRYSUlD8/PW4cEeMZL7kQajwaXVo+J0h3Cn64Mrv3xmLF1tfHN9dq3nPpJBACVH/sEiN4t3WCB/BX9JsJ/lZ0pzIUVxv46ysVUtZ++1hc4HXqwGo3
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: controller-manager
      namespace: github-actions

