apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: github-actions
spec:
  encryptedData:
    github_token: AgAJaK888s0gpBdZeU1Ika8v7CtTC2SlqV/qV/RhQaWKPS2hCfUOdFb/L/bP4RI9OZMq7q20E64wYoPz8mMzbs6xkOOju5QnsCobKOh7xT5bD6TynVcYDeetZVg9a5diPUD0msapd06ZSRkT7sSFfx9LN9hOQ727QuwwgeYyvA7+1LJCc3gznic2SJ9dYmW6ulw0YxGr33nTwpQxsDBH3ge6OPBZw13NacZgB3JSkAPJ8fN+PCAhf3/t94mv3EdWtiOdoQQjTtyxa9jji7EjagHMzXmo5TR8STrBdJHPYqmGTyt/G0LZf32I3v3yTZSJSEcX1GNydSegjgCAHIEANx3drKqeGC2C91kivj7IlGM4bydWi8XM61enpQjZAo8zcnBX1qQYluG7O0ma+bIs9CxluPenbO733Ej69/JW38O46U8vpQNoMEfDjA2wAX5trmNyU4voZqMt7Co0+DTgmoj4NSRAqsNKXNz2+yNyL2bN3GuMhuXpNmYrJHn+j49RqWyjMtqXNrErnHvu2LxqSX4oMpK6iHaDbtl8INt91vuJLKJjxEHTvDsayYYRDDudMQ/JaTpkfcE44ISQXW4Bjees6BCvcVKa8mXIAva0hOwUnksxBJKoWNDNXe2Rxs2hkTRZpnJ0fCinFuXr+5H2Wv6/hJQ8S6jRa+U/og199IhXI2AhkGfGjSjlonCmExGYr8IrOcuE6SrkJnMVu4eGfFBrjL5TzxvwFZ8u8KT1xtaSm1kCf18+fqVm
  template:
    metadata:
      creationTimestamp: null
      name: controller-manager
      namespace: github-actions
    type: Opaque

