#? Github actions 
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: controller-manager
  namespace: github-actions
  annotations: { sealedsecrets.bitnami.com/cluster-wide: "true" }
spec:
  encryptedData:
    github_token: AgBIWrOV5tuC82xVnwKj3yx4vcl0bECs0NoekN4jyVbi5vL3crgyN8x0JjRL07tPt8WxWjARPV9z/QfmJE6IpyDreX8YHqdwWRRd6fkQxxN2KI47X3EOrhCYm6gl7wSbAF04ITpDpnLMSGfUImNoTHqSVc6w4Nul01J+W52uliTzXOqahryFp08srMIDRhAe0znyaZPZzK0ptVpDH5Zj7ynpu32F4G9H62ZoWI1pygBKcwaxEMoL3SJccAE0+9gFFgCeBzeQpdHuv+oU4V27iuEebCmaRIwP53v95R+DDdslZA5Y2CxtYdubr7wRkx5aGSGG9FNvxEq4pB0O5+gYG82TDv31Dw08yzHZE6dZ9IXKU25dbkFmxuyj77sOPUxCvowQLOm+u6MRAmVd675SoQL/hXtUYheWu95IT9mw46cGcP3/S5+k11OLiqe/J79XRarb1YV645y54xQ8F2PASuG6fEraPjyANiUbJFhxG5b1j8+8nMin1t1D4gqcW9WNS/1V9qp09zIv06cFEkkex6fNwD6fLP7oZF3MA0uVvwb0APS9ZM0q/wCK1mfMf+tqNJHg/tAm6CHe2axl9JUvZfDWJPH6DC0HzJFRUSt2IR/cq/YWMrhiG2P5Xv2vdAGBGXlMECyf0dWSSrdSRAhmg+u99ki9HzzoxzzSDMOSOVwFkH3Om/P35vNEfYK7JcD2VObkkvHmILJuYTUzZpyHZatfQTftRDzb7f90W+pcjcbMf+bCK7RJkhzS
