apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: actions
spec:
  encryptedData:
    github_token: AgAPKYsBEcAjVhA9l/UpDn1LTpgNiJf4MkQf8tKzkDzPjMZ2kPukFMyhI714964+mzbeSGkqhjFUiI1atiBd2y0SeyBUpxLKAI8u2nwl81aid7S/AcjbTB71xFx9YNfvaOMcRThsRRu1Im+5Y1HwA/ljNOk89O8+TOz2RAWiEKOHb+n5prDIt+h0nakiJgR1JSCFMkgZB1GbkLNBZxhUhrdegeTiNhLZ/hbUGay8Af6XfDbDdphnFBN2hMvLgfypECRb1jsjEvP1WaRCebpUknwpyCV04QzyTn+fqc6h2N6WwL7i4eucG57WaPj2H9VPeeZjGgmqR/stIwNMvdr5tgZQbFXyB7oIVXEPoQktLCBWx/z1z6dX74y0d8CJJ/luEim5SaoymLlNm1+WcPZm7gRAre58W0x1R8VpqbWmB+fxCrU2iMPL9wpIaS/EJ8AEIE5z+q+6qoxS3H06SUwidd1uEjmsU13+uQiAQdDWeLMThDNX/ms7O3CaPyHR/PP+DKJZ3JI4hoXFw/Al/mgiNU/ETORLtYx9fyjZWVaHg/bDZta7vqdMu+3KiBTV5TU1y7/zyb5sC1Jqe2X253IKBg6Mj+SLfemWQEoRvyJy245hM7fQ8+iSkvxyog2PzW3ZronMrjJP2wF7NEbtNTfaa6L3+f83TDmJL7eJH8Hwe3sOJZqd5pQ9ipinvpaSpLe0rloPoL1DBCNG109Vbh4KWifBywtY1VdhwBtzKy0QCFEexqSMcGW2fVsG
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      creationTimestamp: null
      name: controller-manager
      namespace: actions

