apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: github-actions
spec:
  encryptedData:
    github_token: AgDGZ9/GeDKllXjYYz0FGxTDmKcPaB59TALrro0G1JSsvlLPs6eb3jlW1T5puDdA/M5sqCBibue5y0BtQT5SH3hzF7+cBkcHRDxbXH1u6RUNl5z9bbHCOAcVxOfYCm48JZv/bIb6kotOkqTzAoALH31zYjByVCRIS+kGhekaLe+LzYzSRcIhRxoOzcjrlTlQKmPGc7rldcxvu1p31HrGSSaULGlhiPI+pGO2JeMa/fMPz/flGnxnwKB4bugupkoxKTfNsVJ1noAOhyDHTZe/vIyUJzSrc1hLey/ZcrKdlDlGOlp8yh2YfZQ3Ole3USC8oB2Zs2lnnRaLczgU6k+SfaNTTcNqXbEM06BMvaJAa3XkKXYcH53Kh5xNhXw9VOd3XozrXnrYCnqBXg/VvQ+Qij/3mYUwAnM2sEZuMzI5M43lxCY06pEP2mg2pN9yItGw5cxEQfW2Rd4eQ63l+vwZSwLwfxoMnYIN3SDe+LSFRZxCIi/HBIwnucIc+PRwyG8tBcFc1vZ2timX0ct2/23YXLpTbij/YS5oEkjOHPRjToLEILUFRTbldQb+jpIjWVMEQk2VmsGcbjZlaJvNkiuY92WNrNDP9ybaX0r58lgGbWSReE6cfPh2pEwkXtJxpG4OLWB/lzueSmCqMerHBhtmWjhJ2wW29XOYwkT1iSaPqUquGqp7h9hye1o36c1ALucVVlnjJIyPEsbb2dJfnculeeRbrbjiBP54dC8dz5fqGjsDjP4Z3o5CA1TN
  template:
    metadata:
      creationTimestamp: null
      name: controller-manager
      namespace: github-actions
    type: Opaque

