apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-1
  namespace: actions
spec:
  replicas: 1
  template:
    spec:
      repository: MP281X/argocd
      labels: [argo-runner]
      env: []
