apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: actions-runner-system
spec:
  encryptedData:
    github_token: AgBIvLPZ8qHDGH34OKrbEuhycWlwj97V9zsp64GebiXZH+MOXNNTv2HqD413Y3KrU2Mgy6uftbQJN7h45PIEgMpKMQU141TjkpW49ZBgoMd/MKtrSB1C2gTeX1FrSUXDfQSIZRaWpoyci9mO6m5WeK+gLVwdeaDkragCluoLHBJMYH4p0wV3+HTlp+qy92d8BIbbA70ilNFkMZw6H+NxAu/wcPcT0fN00afPAxoRkuKY3FySPa9/pDB0zE1EfW3ScpCY7rWjU5k7je909gGg2VKbD4zp7cfJmdCYTmEk0B+PP9Q9mIBdHdm+NlDMLt50hjCMTDQgbPziL508R6OQKH1indjn21rAdNor4QZU/c5Og/LhjROKuadeR8kk08kMyEmjY3ZztjXAOjFVv1HjGHn0BfBF2S6HJj+NQ450zYlFKe382L+DAJ/8p12PP13mK8/LCofVAeN8ZLfl8GHS8soploFqBVBI221kVpQmP8LybgTRmYBltVal3zFVPd86F607WHsJ7vHANc+QjKZkedkY+wJtugNiK+WbmqrRQ+zTyjzKp8ljdKmBlMDBSm1XStrfCLXgJB57cFzgo1+ZEKuRf6TDmPS6ZpXdNPv8UXnRinKdL7pFGoqevBnh1GACCMMYTuxBpHK/D6M6qlQVE2CY1/2HUaxFYWVFCFppt3ubkVQcNHucbUynCfUBfpndAAJE7plSgftPkw+OrozZiKqRjfyIjIatsYD4wgdHjvA7+9949SG4CdBL
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: controller-manager
      namespace: actions-runner-system

