apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: actions-runner-systemr
spec:
  encryptedData:
    github_token: AgA91vuuJsXGGMCQLxVjoA3TDi1AslcRDnPp+XN0lV826p4LMqHs0y6w2bxLr1CjAOFDZWRo9xf1BOA2ffjk3J7QZ/3pTwMSt2R4NgMzxcdSyxIkaziB0R3K39uMJTKdpdTWb19wAskvIiJL7Nrr4TW9UrxIm7UCZSUIX/noJjj7hlz3hd1lPrMi47LHKwfNVwZZ+RL3S4kuJ+Je9HeAy6BLWu8dRpif7ARakG6hLZ7hY25NUr/1e3Cj5+mEWsdOcJJIOaz+DeI1ZgB/ayYaqTjr7UWZJFCQsbmbALugDflKvxUwzQ5ZExBLwAIOm4KnSGW7fq5d99yjWK1tzLKSFrrmbsO4uV0/1/DozYY6PA16BCWqN32eqETjn7PD6hhKpesSfLoofp0NjM8AmNOAvzRdQmzgFGOoDwvvepi6n4xhR5f2QKlX9mF8AmIEvQ1FNNNn+GY/mssv1ZpvvKd2hbn5A/XPF4gxSEQmzaoN9dVQ8SorrpVa0gkxKD2jwjIaI+guabTdhWHDDsO0/aXwMfz8YERgM1VzNplgYLHhXLnBzjgZ1mVR3t1hnp0aJ+jk/YjNuFiu+T+e8jbT9Q0VQIVHnMzEZN75gtkOPVx2FFXnUprVMplfdEH/7Gc5VnNRlapRODw0SjLzjZEePdqbe0hZyvU8TWLXtIgJ6YhQtjBPB4HTcbPF3dcOEMVeSiFdeBekeTuQtu08RdA1hXYxFlkuL0D3E33rMbllG92RaC/IwJs2y2wLHg1a
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: controller-manager
      namespace: actions-runner-systemr

