apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: github-actions
spec:
  encryptedData:
    github_token: AgC3tA1ohfD8Dnu7LFRi8rfC3Etkq2eZgDAz4cAAB0KvY7Zw6eyW8yVWnJVSUiEzrN9Dv6FfR2i0JHLOt4Pp7D/JIR25ODHaOLCscyDzscEzUzMCpaVXfGcbddlG9Ckb5GIrc6iU55C8CuRnIbM/dV6YUv+rDFun9Kh4aNgVTPwCEuWvq8YTzD/kUdcku7bds14yUhQfVVybl+fqA88Tq0YT2JHUTMMMFi3k4B963Qwgf5p7+iGcbKAWRrbzYBsIXhaYhkueIF2w+176bOhw/meyFq0jZaN/O8iANesJxp3Qnm7LTUTrsyLY/aiaNcHZZ+fkFRAcXyrtDhFWtaYI0uIxncjN6rw4puNJlq9m2EbPucEOIc6IKZ4BLE1tHvkw0z8k5Ft8blLBtkTKjlym+Dg/iDDrhoMMZbFnCbgCiG3/wMi3YKGRmthFePpcH9BrbJGh74lIwVV0ZUdj0mLxqi37Se3g2K3REjuuCKU943Ufgb5GC2g3E0RsVF6NIINXPanwcoaSaUY+y1e7uZb0UeaSENpoSUJghV+0HdM2FGCO42FbbIAysZNEYG0EGCCdBXjh7TZJzJn1D3xBYLVM5PZsFsXakPUUlZKI/q2QuRZ2cb4TaZEJuc7HL7S0psDiVYjtqH+P8K04ToUXW0slWAdNiwWzAxfLbc4mYXeV6u94YWgcG9YhVSenwScHBct0vYzO5oo4dzT0BdNr07e5FPkTr4qfYcLa71p+qwhCAlcxUScXldezAyOJ
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      creationTimestamp: null
      name: controller-manager
      namespace: github-actions

