apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: actions-runner-system
spec:
  encryptedData:
    github_token: AgAPqudAr16gj396lHUKWGlKmQ+/XnSHu0zIDSXX8rBRC7DSgHF0RbbRRT/dozHme6K1kE+bydfckfwYrXUuyyyXadz+he4BA78D/JGlvMvOSTahPj1NnGMAhGnTJDsDVt2LJgSsyeTgEFb/GAZbbX7X7429QQxu9v4wfdDnI3cVDsAaQj4e2HDWHr8iVVWqP8/zGE5hfZxuoHlGlOiPKmvS5qHpVthQCOYnUpl2XjlFUb6DNoCL9gQyHg38lH1M+ny01cs1J3rPg/X4qP+edFzE5GNb/b+YGsiaRA9/cd40Vp+GfbZGpFtTwRyvYqHjqqxGuA11wtu8wTsJa5+uBPX3UbC7wvHWVpYTzGm3CLR8nGv/fM/G+H7gehVmtACb3vUJqQM1uCkHJvnvV2EODuF+AI3wyaRku+ANQMQfjMlEslc6MRFPfw1EoJLYWqX3NNe1u24dvTlzEf7kZ4CnQj1oaVsOXmjPrMPrE7WARXhGI3o2HFTjer3BguS+hGK1Utk2fw5U4ldBz4bB5eI+bWoFlH6kKPS4nnq9r3lD+9crqRxrielXZD4B98euEc+KzfpZLnIMgPjQOhJlfe/72mfZYGgUs56iZEeSeoosgqFg5riiRSzAOMLQJ5hGPo3eB5oI1Eg6vkSj5e1k4Md1ATmrfJr1MQFG+3SPRI7WLQuuYc05vjEC/hY/NoaXuYsiJbqb6aBpRgwCJFDg2PcF7ykdTXpzxoE1yQcfNGrLi5A5aI89CgNdxrIX
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: controller-manager
      namespace: actions-runner-system

