apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: infrastructure
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 10.24.0
    helm:
      values: |-
        globalArguments:
          - "--global.sendanonymoususage=false"
          - "--global.checknewversion=false"
        additionalArguments:
          - "--serversTransport.insecureSkipVerify=true"
          - "--log.level=INFO"

        ports:
          web: { redirectTo: websecure }
          websecure: { tls: { enabled: true } }

        ingressRoute: { dashboard: { enabled: false } }
        rbac: { enabled: true }

        providers:
          kubernetesCRD:
            enabled: true
            ingressClass: traefik
          kubernetesIngress:
            enabled: true
            publishedService: { enabled: true }

        service:
          ipFamilyPolicy: "PreferDualStack"

  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions: [CreateNamespace=true]
    automated: { prune: true, selfHeal: true }
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`traefik.local.mp281x.xyz`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
