apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: infrastructure
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 10.24.0
    helm:
      values: |-
        globalArguments:
          - "--global.sendanonymoususage=false"
          - "--global.checknewversion=false"
        additionalArguments:
          - "--log.format=json"
          - "--serversTransport.insecureSkipVerify=true"

        ports: { web: { redirectTo: websecure } }
        ingressRoute: { dashboard: { enabled: false } }
        service: { ipFamilyPolicy: "PreferDualStack" }
        providers:
          kubernetesCRD: { enabled: true, ingressClass: traefik }
          kubernetesIngress: { enabled: true, publishedService: { enabled: true } }
