name: Build node js runner
on: { push: { paths: ["app/github-actions/github-runner/docker/**"] } }
jobs:
  Build-node-js-runner:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -f ./app/github-actions/github-runner/docker/node-runner.Dockerfile -t ghcr.io/mp281x/node-runner:latest .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: mp281x
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker push
        run: docker push ghcr.io/mp281x/node-runner:latest
