name: Create and publish a Docker image

on: { push: { paths: ["Dockerfile"] } }

jobs:
  build-and-push-image:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/mp281x/test-container:latest

      - name: Push docker image
        run: docker push ghcr.io/mp281x/test-container:latest

      - name: Keel Webhook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: "https://keel.mp281x.xyz/v1/webhooks/native"
          webhook_secret: "password"
          data: '{ "tag": "latest", "name": "ghcr.io/mp281x/test-container" }'
